/**
 * **Erzeugt von `packages/ingest/src/build-zone-keys.ts` — nicht von Hand ändern.**
 *
 * Die gültigen Zonenkennungen je Stadt, gelesen aus den ausgelieferten
 * `zones.geojson`. Der Worker prüft die Ausprägung von `zone.open` dagegen;
 * ohne diese Liste wäre sie eine Freitextspalte.
 *
 * Neu erzeugen, nachdem sich die Daten geändert haben:
 *
 * ```bash
 * cd app/packages/ingest && npx tsx src/build-zone-keys.ts
 * ```
 */

export const ZONE_KEYS: Readonly<Record<string, readonly string[]>> = {
  "berlin": [
    "1",
    "10",
    "100",
    "101",
    "105",
    "106",
    "11",
    "12",
    "120",
    "121",
    "126",
    "127",
    "128",
    "129",
    "13",
    "130",
    "131",
    "132",
    "133",
    "134",
    "135",
    "136",
    "137",
    "138",
    "14",
    "15",
    "16",
    "17-CW",
    "17-TS",
    "18",
    "19",
    "2",
    "20",
    "21",
    "22",
    "23",
    "24",
    "25",
    "26",
    "27",
    "28",
    "29",
    "3",
    "30",
    "33",
    "34",
    "35",
    "36",
    "37",
    "38",
    "4",
    "40",
    "41-Mitte",
    "41-Pankow",
    "42",
    "43",
    "44",
    "45",
    "46",
    "49",
    "5",
    "50",
    "51-Arena Süd",
    "51-OberbaumCity",
    "54",
    "55",
    "6",
    "60",
    "61",
    "63",
    "64",
    "65",
    "66",
    "67",
    "68",
    "69",
    "7",
    "70",
    "71",
    "72",
    "73",
    "74",
    "75",
    "76",
    "77",
    "78",
    "79",
    "8",
    "80",
    "81",
    "82",
    "83",
    "84",
    "85",
    "86",
    "87",
    "88",
    "89",
    "9-CW",
    "9-TS",
    "90",
    "91",
    "92",
  ],
  "hamburg": [
    "-",
    "A100",
    "A101",
    "A102",
    "A103",
    "A104",
    "A105",
    "A106",
    "A107",
    "A108",
    "A109",
    "A110",
    "AE100",
    "AE101",
    "AE102",
    "AE103",
    "E300",
    "E301",
    "E302",
    "E303",
    "E304",
    "E305",
    "E306",
    "E307",
    "E308",
    "E309",
    "E310",
    "E311",
    "E312",
    "E313",
    "E314",
    "E315",
    "E316",
    "M100",
    "M101",
    "M102",
    "M103",
    "M104",
    "M105",
    "M106",
    "M107",
    "M108",
    "M109",
    "M110",
    "M111",
    "MA201",
    "MA202",
    "MA203",
    "MA204",
    "N100",
    "N101",
    "N102",
    "N103",
    "N104",
    "N105",
    "N106",
    "N107",
    "N108",
    "N109",
    "N110",
    "N111",
    "N112",
    "N113",
  ],
  "frankfurt": [
    "0",
    "10",
    "12",
    "13",
    "15",
    "16",
    "17",
    "18",
    "19",
    "20",
    "21",
    "22",
    "25",
    "26",
    "29",
    "31",
    "32",
    "35",
    "38",
    "39",
    "4",
    "40",
    "41",
    "6",
    "7",
    "8",
    "9",
  ],
  "muenchen": [
    "Akademieviertel",
    "Albrechtstraße",
    "Alte Heide",
    "Alter Südfriedhof",
    "Altschwabing",
    "Altstadt",
    "Apostelblöcke",
    "Barbarastraße",
    "Bayernplatz",
    "Biederstein",
    "Borstei",
    "Brudermühlviertel",
    "Clemensstraße",
    "Domagpark",
    "Dreimühlenviertel",
    "Ebenau",
    "Eichendorffplatz",
    "Franziskanerstraße",
    "Franzosenviertel",
    "Freiham",
    "Giesinger Bahnhof",
    "Giselastraße",
    "Glockenbachviertel",
    "Grillparzerstraße",
    "Gärtnerplatz",
    "Hauptbahnhof",
    "Herzog-Ernst-Platz",
    "Heßstraße",
    "Innenstadtklinikum",
    "Karolinenplatz",
    "Karwendelstraße",
    "Kasernenviertel",
    "Kirchenstraße",
    "Klinikviertel",
    "Kölner Platz",
    "Königsplatz",
    "Lerchenauer Straße",
    "Lindwurmstraße",
    "Margaretenplatz",
    "Marsfeld",
    "Messestadt",
    "Mittleres Lehel",
    "Nördliche Au",
    "Nördliche Passauerstraße",
    "Nördliches Lehel",
    "Partnachplatz",
    "Pasing Süd",
    "Pinakotheken",
    "Potsdamer Straße",
    "Regerplatz",
    "Ridlerstraße",
    "Rotkreuzplatz Nord",
    "Rotkreuzplatz Süd",
    "Schleißheimer Straße",
    "Schwabing Mitte",
    "Schwanthalerhöhe",
    "Schyrenbad",
    "Schönfeldviertel",
    "Schönstraße Nord",
    "Schönstraße Süd",
    "Seydlitzplatz",
    "Silberhornstr.",
    "St.-Benno-Viertel",
    "St.-Martins-Platz",
    "St.-Pauls-Viertel",
    "St.-Vinzenz-Viertel",
    "Südliche Au",
    "Südliche Hansastraße",
    "Südliches Lehel",
    "TU-Viertel",
    "Tegernseer Landstr.",
    "Thalkirchen",
    "Theresienhöhe",
    "Tristanstraße",
    "Untergiesing",
    "Untersendling",
    "Volkartstraße",
    "Walchenseeplatz",
    "West Schwabing",
    "Westend",
    "Wettersteinplatz",
    "Winzererstraße",
  ],
}

/** Alle Kennungen aller Städte, für eine Prüfung ohne Stadtbezug. */
export const ALL_ZONE_KEYS: readonly string[] = Object.values(ZONE_KEYS).flat()
