/**
 * ERZEUGT von `packages/ingest/src/build-zone-units.ts` — nicht von Hand ändern.
 *
 * Je Stadt: Zonenschlüssel → Einheit der Langzeitmuster. Eine Zone unter
 * 2 ha (Karlsruhes Stellplatzreihen, Hamburgs kleine Flächen) zählt für
 * ihren Bezirk, alle anderen für sich. `zone-units-aktuell.test.ts` hält
 * die Datei gegen die ausgelieferten Daten; der Befehl steht dort.
 */

export const ZONE_UNITS: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  "berlin": {
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "10": "10",
    "11": "11",
    "12": "12",
    "13": "13",
    "14": "14",
    "15": "15",
    "16": "16",
    "18": "18",
    "19": "19",
    "20": "20",
    "21": "21",
    "22": "22",
    "23": "23",
    "24": "24",
    "25": "25",
    "26": "26",
    "27": "27",
    "28": "28",
    "29": "29",
    "30": "30",
    "33": "33",
    "34": "34",
    "35": "35",
    "36": "36",
    "37": "37",
    "38": "38",
    "40": "40",
    "42": "42",
    "43": "43",
    "44": "44",
    "45": "45",
    "46": "46",
    "49": "49",
    "50": "50",
    "54": "54",
    "55": "55",
    "60": "60",
    "61": "61",
    "63": "63",
    "64": "64",
    "65": "65",
    "66": "66",
    "67": "67",
    "68": "68",
    "69": "69",
    "70": "70",
    "71": "71",
    "72": "72",
    "73": "73",
    "74": "74",
    "75": "75",
    "76": "76",
    "77": "77",
    "78": "78",
    "79": "79",
    "80": "80",
    "81": "81",
    "82": "82",
    "83": "83",
    "84": "84",
    "85": "85",
    "86": "86",
    "87": "87",
    "88": "88",
    "89": "89",
    "90": "90",
    "91": "91",
    "92": "92",
    "100": "100",
    "101": "101",
    "105": "105",
    "106": "106",
    "120": "120",
    "121": "121",
    "126": "126",
    "127": "127",
    "128": "128",
    "129": "129",
    "130": "130",
    "131": "131",
    "132": "132",
    "133": "133",
    "134": "134",
    "135": "135",
    "136": "136",
    "137": "137",
    "138": "138",
    "17-CW": "17-CW",
    "17-TS": "17-TS",
    "41-Mitte": "41-Mitte",
    "41-Pankow": "41-Pankow",
    "51-Arena Süd": "51-Arena Süd",
    "51-OberbaumCity": "51-OberbaumCity",
    "9-CW": "9-CW",
    "9-TS": "9-TS",
  },
  "hamburg": {
    "A100": "A100",
    "A101": "A101",
    "A102": "A102",
    "A103": "A103",
    "A104": "A104",
    "A105": "A105",
    "A106": "A106",
    "A107": "A107",
    "A108": "A108",
    "A109": "A109",
    "A110": "A110",
    "AE100": "AE100",
    "AE101": "AE101",
    "AE102": "AE102",
    "AE103": "AE103",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32004": "bezirk:Rotherbaum",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32005": "DE.HH.UP_BEWOHNERPARKGEBIETE_32005",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32006": "bezirk:Rotherbaum",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32007": "bezirk:Rotherbaum",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32008": "bezirk:Ottensen",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32009": "bezirk:Ottensen",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32011": "bezirk:Ottensen",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32012": "bezirk:Altona-Altstadt",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32013": "bezirk:Ottensen",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32015": "bezirk:Altona-Altstadt",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32017": "bezirk:Altona-Altstadt",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32018": "bezirk:Ottensen",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32019": "bezirk:Altona-Altstadt",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32020": "bezirk:Ottensen",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32022": "bezirk:Altona-Altstadt",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32023": "bezirk:Altona-Nord",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32028": "DE.HH.UP_BEWOHNERPARKGEBIETE_32028",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32029": "bezirk:St. Georg",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32030": "bezirk:St. Georg",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32031": "bezirk:St. Georg",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32032": "bezirk:St. Georg",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32033": "bezirk:St. Georg",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32034": "bezirk:Hammerbrook",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32035": "bezirk:Altona-Altstadt",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32039": "bezirk:St. Pauli",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32045": "bezirk:St. Georg",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32046": "bezirk:Hammerbrook",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32047": "bezirk:Hammerbrook",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32052": "bezirk:Harvestehude",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32053": "bezirk:Harvestehude",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32061": "DE.HH.UP_BEWOHNERPARKGEBIETE_32061",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32063": "bezirk:Lokstedt",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32069": "bezirk:Eimsbüttel",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32076": "bezirk:Eppendorf",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32078": "bezirk:Eppendorf",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32082": "bezirk:Lokstedt",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32084": "bezirk:Lokstedt",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32086": "DE.HH.UP_BEWOHNERPARKGEBIETE_32086",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32087": "bezirk:Hoheluft-Ost",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32088": "bezirk:Eppendorf",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32089": "bezirk:Eppendorf",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32106": "DE.HH.UP_BEWOHNERPARKGEBIETE_32106",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32107": "bezirk:Uhlenhorst",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32108": "bezirk:Uhlenhorst",
    "E300": "E300",
    "E301": "E301",
    "E302": "E302",
    "E303": "E303",
    "E304": "E304",
    "E305": "E305",
    "E306": "E306",
    "E307": "E307",
    "E308": "E308",
    "E309": "E309",
    "E310": "E310",
    "E311": "E311",
    "E312": "E312",
    "E313": "E313",
    "E314": "E314",
    "E315": "E315",
    "E316": "E316",
    "M100": "M100",
    "M101": "M101",
    "M102": "M102",
    "M103": "M103",
    "M104": "M104",
    "M105": "M105",
    "M106": "M106",
    "M107": "M107",
    "M108": "M108",
    "M109": "M109",
    "M110": "M110",
    "M111": "M111",
    "MA201": "MA201",
    "MA202": "MA202",
    "MA203": "MA203",
    "MA204": "MA204",
    "N100": "N100",
    "N101": "N101",
    "N102": "N102",
    "N103": "N103",
    "N104": "N104",
    "N105": "N105",
    "N106": "N106",
    "N107": "N107",
    "N108": "N108",
    "N109": "N109",
    "N110": "N110",
    "N111": "N111",
    "N112": "N112",
    "N113": "N113",
  },
  "frankfurt": {
    "0": "0",
    "4": "4",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "10": "10",
    "12": "12",
    "13": "13",
    "15": "15",
    "16": "16",
    "17": "17",
    "18": "18",
    "19": "19",
    "20": "20",
    "21": "21",
    "22": "22",
    "25": "25",
    "26": "26",
    "29": "29",
    "31": "31",
    "32": "32",
    "35": "35",
    "38": "38",
    "39": "39",
    "40": "40",
    "41": "41",
  },
  "muenchen": {
    "Akademieviertel": "Akademieviertel",
    "Albrechtstraße": "Albrechtstraße",
    "Alte Heide": "Alte Heide",
    "Alter Südfriedhof": "Alter Südfriedhof",
    "Altschwabing": "Altschwabing",
    "Altstadt": "Altstadt",
    "Apostelblöcke": "Apostelblöcke",
    "Barbarastraße": "Barbarastraße",
    "Bayernplatz": "Bayernplatz",
    "Biederstein": "Biederstein",
    "Borstei": "Borstei",
    "Brudermühlviertel": "Brudermühlviertel",
    "Clemensstraße": "Clemensstraße",
    "Domagpark": "Domagpark",
    "Dreimühlenviertel": "Dreimühlenviertel",
    "Ebenau": "Ebenau",
    "Eichendorffplatz": "Eichendorffplatz",
    "Franziskanerstraße": "Franziskanerstraße",
    "Franzosenviertel": "Franzosenviertel",
    "Freiham": "Freiham",
    "Gärtnerplatz": "Gärtnerplatz",
    "Giesinger Bahnhof": "Giesinger Bahnhof",
    "Giselastraße": "Giselastraße",
    "Glockenbachviertel": "Glockenbachviertel",
    "Grillparzerstraße": "Grillparzerstraße",
    "Hauptbahnhof": "Hauptbahnhof",
    "Herzog-Ernst-Platz": "Herzog-Ernst-Platz",
    "Heßstraße": "Heßstraße",
    "Innenstadtklinikum": "Innenstadtklinikum",
    "Karolinenplatz": "Karolinenplatz",
    "Karwendelstraße": "Karwendelstraße",
    "Kasernenviertel": "Kasernenviertel",
    "Kirchenstraße": "Kirchenstraße",
    "Klinikviertel": "Klinikviertel",
    "Kölner Platz": "Kölner Platz",
    "Königsplatz": "Königsplatz",
    "Lerchenauer Straße": "Lerchenauer Straße",
    "Lindwurmstraße": "Lindwurmstraße",
    "Margaretenplatz": "Margaretenplatz",
    "Marsfeld": "Marsfeld",
    "Messestadt": "Messestadt",
    "Mittleres Lehel": "Mittleres Lehel",
    "Nördliche Au": "Nördliche Au",
    "Nördliche Passauerstraße": "Nördliche Passauerstraße",
    "Nördliches Lehel": "Nördliches Lehel",
    "Partnachplatz": "Partnachplatz",
    "Pasing Süd": "Pasing Süd",
    "Pinakotheken": "Pinakotheken",
    "Potsdamer Straße": "Potsdamer Straße",
    "Regerplatz": "Regerplatz",
    "Ridlerstraße": "Ridlerstraße",
    "Rotkreuzplatz Nord": "Rotkreuzplatz Nord",
    "Rotkreuzplatz Süd": "Rotkreuzplatz Süd",
    "Schleißheimer Straße": "Schleißheimer Straße",
    "Schönfeldviertel": "Schönfeldviertel",
    "Schönstraße Nord": "Schönstraße Nord",
    "Schönstraße Süd": "Schönstraße Süd",
    "Schwabing Mitte": "Schwabing Mitte",
    "Schwanthalerhöhe": "Schwanthalerhöhe",
    "Schyrenbad": "Schyrenbad",
    "Seydlitzplatz": "Seydlitzplatz",
    "Silberhornstr.": "Silberhornstr.",
    "St.-Benno-Viertel": "St.-Benno-Viertel",
    "St.-Martins-Platz": "St.-Martins-Platz",
    "St.-Pauls-Viertel": "St.-Pauls-Viertel",
    "St.-Vinzenz-Viertel": "St.-Vinzenz-Viertel",
    "Südliche Au": "Südliche Au",
    "Südliche Hansastraße": "Südliche Hansastraße",
    "Südliches Lehel": "Südliches Lehel",
    "Tegernseer Landstr.": "Tegernseer Landstr.",
    "Thalkirchen": "Thalkirchen",
    "Theresienhöhe": "Theresienhöhe",
    "Tristanstraße": "Tristanstraße",
    "TU-Viertel": "TU-Viertel",
    "Untergiesing": "Untergiesing",
    "Untersendling": "Untersendling",
    "Volkartstraße": "Volkartstraße",
    "Walchenseeplatz": "Walchenseeplatz",
    "West Schwabing": "West Schwabing",
    "Westend": "Westend",
    "Wettersteinplatz": "Wettersteinplatz",
    "Winzererstraße": "Winzererstraße",
  },
  "koeln": {
    "Agnesviertel I": "Agnesviertel I",
    "Agnesviertel II": "Agnesviertel II",
    "Belgisches Viertel": "Belgisches Viertel",
    "City-Martinsviertel": "City-Martinsviertel",
    "Deutz I": "Deutz I",
    "Deutz II": "Deutz II",
    "Deutz III": "Deutz III",
    "Deutz V": "Deutz V",
    "Ehrenfeld I": "Ehrenfeld I",
    "Ehrenfeld II": "Ehrenfeld II",
    "Ehrenfeld III": "Ehrenfeld III",
    "Ehrenfeld IV": "Ehrenfeld IV",
    "Eigelstein": "Eigelstein",
    "Georgsviertel": "Georgsviertel",
    "Gereonsviertel": "Gereonsviertel",
    "Griechenmarktviertel": "Griechenmarktviertel",
    "Hohenlind": "Hohenlind",
    "Hültzviertel": "Hültzviertel",
    "Kalk": "Kalk",
    "Keupstr.": "Keupstr.",
    "Kunibertsviertel": "Kunibertsviertel",
    "Lindenthal-Nord I": "Lindenthal-Nord I",
    "Lindenthal-Nord II": "Lindenthal-Nord II",
    "Lindenthal-Süd I": "Lindenthal-Süd I",
    "Lindenthal-Süd II": "Lindenthal-Süd II",
    "Mülheim": "Mülheim",
    "Nippes": "Nippes",
    "Nippes EAW": "Nippes EAW",
    "Nippes I": "Nippes I",
    "Nippes II": "Nippes II",
    "Nippes III": "Nippes III",
    "Nippes IV": "Nippes IV",
    "Nördlich Neumarkt": "Nördlich Neumarkt",
    "Nördliche Neustadt": "Nördliche Neustadt",
    "Pantaleonsviertel": "Pantaleonsviertel",
    "Porz-City": "Porz-City",
    "Rathenauviertel": "Rathenauviertel",
    "Severinsviertel": "Severinsviertel",
    "Südbahnhof": "Südbahnhof",
    "Südliche Neustadt I": "Südliche Neustadt I",
    "Südliche Neustadt II": "Südliche Neustadt II",
    "Sülz-Nord I": "Sülz-Nord I",
    "Sülz-Nord II": "Sülz-Nord II",
    "Weiden Nord": "Weiden Nord",
    "Weiden Süd": "Weiden Süd",
  },
  "duesseldorf": {
    "Ahnfeldstraße (AS)": "Ahnfeldstraße (AS)",
    "Altstadt - Nord (K)": "Altstadt - Nord (K)",
    "Altstadt (A)": "Altstadt (A)",
    "Blücherstraße (S)": "Blücherstraße (S)",
    "Christophstraße (CH)": "Christophstraße (CH)",
    "Daimler (B)": "Daimler (B)",
    "Derendorf (Q)": "Derendorf (Q)",
    "Derendorfer Straße (W)": "Derendorfer Straße (W)",
    "Feldstraße (H)": "Feldstraße (H)",
    "Feuerbachstraße (FB)": "Feuerbachstraße (FB)",
    "Flughafen (F)": "Flughafen (F)",
    "Friedrichstadt (N)": "Friedrichstadt (N)",
    "Gerresheimer Straße (GS)": "Gerresheimer Straße (GS)",
    "Golzheim - Rolandstraße (C)": "Golzheim - Rolandstraße (C)",
    "Golzheimer Platz (GP)": "Golzheimer Platz (GP)",
    "Hasselsstraße (X)": "bezirk:Hassels",
    "Hauptbahnhof - Ost (HO)": "Hauptbahnhof - Ost (HO)",
    "Henkelgebiet (M)": "Henkelgebiet (M)",
    "Hermannplatz (HP)": "Hermannplatz (HP)",
    "Immermannstraße (O)": "Immermannstraße (O)",
    "Inselstraße (J)": "Inselstraße (J)",
    "Kaiserswerth (V)": "Kaiserswerth (V)",
    "Kanzlerstraße (T)": "Kanzlerstraße (T)",
    "Klosterstraße (L)": "Klosterstraße (L)",
    "Lessingplatz (LP)": "Lessingplatz (LP)",
    "Lichtenbroich (LB)": "Lichtenbroich (LB)",
    "Moorenplatz (MP)": "Moorenplatz (MP)",
    "Moorenstraße (MS)": "Moorenstraße (MS)",
    "Münsterstraße (MÜ)": "Münsterstraße (MÜ)",
    "Neuwerker-, Viersener Straße (NV)": "Neuwerker-, Viersener Straße (NV)",
    "Niederkassel (NK)": "Niederkassel (NK)",
    "Oberkassel - Ost (OK)": "Oberkassel - Ost (OK)",
    "Oberkassel - West (Z)": "Oberkassel - West (Z)",
    "Pempelforter Straße (P)": "Pempelforter Straße (P)",
    "Reeser Platz (RP)": "Reeser Platz (RP)",
    "Schanzenstraße (SC)": "Schanzenstraße (SC)",
    "Schillerplatz (SP)": "Schillerplatz (SP)",
    "Stockum - Blumenviertel (U)": "Stockum - Blumenviertel (U)",
    "Unterbilk (R)": "Unterbilk (R)",
    "Unterrath - Ost (D)": "Unterrath - Ost (D)",
    "Unterrath - West (E)": "Unterrath - West (E)",
    "Unterrath (UR)": "Unterrath (UR)",
    "Venloer Straße (G)": "Venloer Straße (G)",
    "Wersten - Düsseldörfchen (Y)": "Wersten - Düsseldörfchen (Y)",
  },
  "karlsruhe": {
    "1": "bezirk:Durlach",
    "2": "bezirk:Innenstadt-West",
    "4": "bezirk:Südweststadt",
    "5": "bezirk:Durlach",
    "6": "bezirk:Südweststadt",
    "7": "bezirk:Innenstadt-West",
    "8": "bezirk:Innenstadt-West",
    "9": "bezirk:Innenstadt-West",
    "10": "bezirk:Innenstadt-West",
    "11": "bezirk:Innenstadt-West",
    "12": "bezirk:Innenstadt-West",
    "13": "bezirk:Innenstadt-West",
    "14": "bezirk:Südweststadt",
    "15": "bezirk:Innenstadt-Ost",
    "16": "bezirk:Innenstadt-Ost",
    "17": "bezirk:Südstadt",
    "18": "bezirk:Oststadt",
    "19": "bezirk:Mühlburg",
    "20": "bezirk:Südweststadt",
    "21": "bezirk:Südweststadt",
    "22": "bezirk:Südweststadt",
    "23": "bezirk:Rüppurr",
    "24": "bezirk:Südweststadt",
    "25": "bezirk:Innenstadt-West",
    "26": "bezirk:Innenstadt-West",
    "27": "bezirk:Innenstadt-West",
    "28": "bezirk:Innenstadt-West",
    "29": "bezirk:Innenstadt-West",
    "30": "bezirk:Südweststadt",
    "31": "bezirk:Südweststadt",
    "32": "bezirk:Südweststadt",
    "33": "bezirk:Durlach",
    "34": "bezirk:Durlach",
    "35": "bezirk:Durlach",
    "36": "bezirk:Durlach",
    "37": "bezirk:Südweststadt",
    "38": "bezirk:Südweststadt",
    "39": "bezirk:Südweststadt",
    "40": "bezirk:Südweststadt",
    "41": "bezirk:Südweststadt",
    "42": "bezirk:Südstadt",
    "43": "bezirk:Südstadt",
    "44": "bezirk:Innenstadt-West",
    "45": "bezirk:Mühlburg",
    "46": "bezirk:Oststadt",
    "47": "bezirk:Mühlburg",
    "48": "bezirk:Innenstadt-Ost",
    "49": "bezirk:Durlach",
    "50": "bezirk:Weststadt",
    "51": "bezirk:Durlach",
    "52": "bezirk:Durlach",
    "53": "bezirk:Durlach",
    "54": "bezirk:Oststadt",
    "55": "bezirk:Oststadt",
    "57": "bezirk:Innenstadt-Ost",
    "58": "bezirk:Innenstadt-Ost",
    "59": "bezirk:Südweststadt",
    "60": "bezirk:Oststadt",
    "61": "bezirk:Südweststadt",
    "62": "bezirk:Innenstadt-West",
    "63": "bezirk:Mühlburg",
    "64": "bezirk:Innenstadt-West",
    "65": "bezirk:Innenstadt-Ost",
    "66": "bezirk:Innenstadt-West",
    "67": "bezirk:Innenstadt-West",
    "68": "bezirk:Innenstadt-West",
    "69": "bezirk:Innenstadt-Ost",
    "70": "bezirk:Innenstadt-Ost",
    "71": "bezirk:Innenstadt-West",
    "72": "bezirk:Innenstadt-West",
    "73": "bezirk:Innenstadt-West",
    "74": "bezirk:Innenstadt-West",
    "75": "bezirk:Innenstadt-West",
    "76": "bezirk:Innenstadt-West",
    "77": "bezirk:Oberreut",
    "78": "bezirk:Innenstadt-West",
    "79": "bezirk:Weststadt",
    "80": "bezirk:Innenstadt-West",
    "81": "bezirk:Innenstadt-West",
    "82": "bezirk:Innenstadt-West",
    "83": "bezirk:Südweststadt",
    "84": "bezirk:Oststadt",
    "85": "bezirk:Durlach",
    "86": "bezirk:Südweststadt",
    "87": "bezirk:Südweststadt",
    "88": "bezirk:Südweststadt",
    "89": "bezirk:Südweststadt",
    "90": "bezirk:Südweststadt",
    "91": "bezirk:Südweststadt",
    "92": "bezirk:Weststadt",
    "93": "bezirk:Weststadt",
    "94": "bezirk:Innenstadt-Ost",
    "95": "bezirk:Südweststadt",
    "96": "bezirk:Innenstadt-West",
    "97": "bezirk:Innenstadt-West",
    "98": "bezirk:Südweststadt",
    "99": "bezirk:Südweststadt",
    "100": "bezirk:Innenstadt-West",
    "101": "bezirk:Innenstadt-West",
    "102": "bezirk:Nordweststadt",
    "103": "bezirk:Nordweststadt",
    "104": "bezirk:Südweststadt",
    "105": "bezirk:Mühlburg",
    "106": "bezirk:Innenstadt-West",
    "107": "bezirk:Weststadt",
    "108": "bezirk:Weststadt",
    "109": "bezirk:Weststadt",
    "110": "bezirk:Südstadt",
    "112": "bezirk:Innenstadt-Ost",
    "113": "bezirk:Durlach",
    "114": "bezirk:Südweststadt",
    "115": "bezirk:Südweststadt",
    "116": "bezirk:Innenstadt-West",
    "117": "bezirk:Durlach",
    "118": "bezirk:Durlach",
    "119": "bezirk:Innenstadt-West",
    "121": "bezirk:Weststadt",
    "122": "bezirk:Südweststadt",
    "123": "bezirk:Rüppurr",
    "124": "bezirk:Mühlburg",
    "125": "bezirk:Innenstadt-West",
    "126": "bezirk:Weststadt",
    "127": "bezirk:Südweststadt",
    "128": "bezirk:Innenstadt-West",
    "129": "bezirk:Innenstadt-West",
    "131": "bezirk:Südstadt",
    "132": "bezirk:Innenstadt-West",
    "133": "bezirk:Innenstadt-West",
    "134": "bezirk:Innenstadt-West",
    "135": "bezirk:Innenstadt-Ost",
    "136": "bezirk:Innenstadt-West",
    "137": "bezirk:Innenstadt-West",
    "138": "bezirk:Innenstadt-West",
    "139": "bezirk:Innenstadt-West",
    "140": "bezirk:Innenstadt-West",
    "141": "bezirk:Innenstadt-West",
    "142": "bezirk:Innenstadt-Ost",
    "143": "bezirk:Innenstadt-West",
    "144": "bezirk:Südweststadt",
    "146": "bezirk:Südweststadt",
    "147": "bezirk:Südweststadt",
    "148": "bezirk:Durlach",
    "149": "bezirk:Innenstadt-West",
    "150": "bezirk:Weststadt",
    "151": "bezirk:Südstadt",
    "152": "bezirk:Südstadt",
    "153": "bezirk:Südstadt",
    "154": "bezirk:Südstadt",
    "155": "bezirk:Südweststadt",
    "156": "bezirk:Südweststadt",
    "157": "bezirk:Nordstadt",
    "158": "bezirk:Mühlburg",
    "159": "bezirk:Mühlburg",
    "160": "bezirk:Innenstadt-Ost",
    "161": "bezirk:Innenstadt-West",
    "162": "bezirk:Weststadt",
    "163": "bezirk:Südweststadt",
    "164": "bezirk:Südstadt",
    "165": "bezirk:Durlach",
    "166": "bezirk:Durlach",
    "167": "bezirk:Südweststadt",
    "169": "bezirk:Durlach",
    "170": "bezirk:Mühlburg",
    "171": "bezirk:Oststadt",
    "172": "bezirk:Innenstadt-Ost",
    "173": "bezirk:Südweststadt",
    "174": "bezirk:Weststadt",
    "175": "bezirk:Innenstadt-West",
    "176": "bezirk:Südweststadt",
    "177": "bezirk:Innenstadt-West",
    "178": "bezirk:Weststadt",
    "179": "bezirk:Innenstadt-Ost",
    "180": "bezirk:Innenstadt-West",
    "181": "bezirk:Weststadt",
    "182": "bezirk:Nordweststadt",
    "183": "bezirk:Nordweststadt",
    "184": "bezirk:Nordweststadt",
    "185": "bezirk:Nordweststadt",
    "186": "bezirk:Südweststadt",
    "187": "bezirk:Südweststadt",
    "188": "bezirk:Südweststadt",
    "189": "bezirk:Südweststadt",
    "190": "bezirk:Südweststadt",
    "191": "bezirk:Südweststadt",
    "192": "bezirk:Südweststadt",
    "193": "bezirk:Südweststadt",
    "194": "bezirk:Weststadt",
    "195": "bezirk:Oststadt",
    "196": "bezirk:Innenstadt-West",
    "197": "bezirk:Innenstadt-West",
    "198": "bezirk:Innenstadt-West",
    "199": "bezirk:Weststadt",
    "200": "bezirk:Innenstadt-West",
    "201": "bezirk:Südweststadt",
    "202": "bezirk:Südweststadt",
    "203": "bezirk:Südstadt",
    "204": "bezirk:Innenstadt-Ost",
    "205": "bezirk:Mühlburg",
    "206": "bezirk:Südweststadt",
    "207": "bezirk:Südstadt",
    "208": "bezirk:Innenstadt-West",
    "209": "bezirk:Weststadt",
    "210": "bezirk:Oststadt",
    "211": "bezirk:Oststadt",
    "212": "bezirk:Oststadt",
    "213": "bezirk:Oststadt",
    "214": "bezirk:Oststadt",
    "215": "bezirk:Oststadt",
    "216": "bezirk:Oststadt",
    "217": "bezirk:Oststadt",
    "218": "bezirk:Oststadt",
    "219": "bezirk:Oststadt",
    "220": "bezirk:Oststadt",
    "221": "bezirk:Durlach",
    "222": "bezirk:Südstadt",
    "223": "bezirk:Innenstadt-West",
    "224": "bezirk:Innenstadt-West",
    "225": "bezirk:Innenstadt-West",
    "226": "bezirk:Innenstadt-West",
    "227": "bezirk:Innenstadt-West",
    "228": "bezirk:Innenstadt-Ost",
    "229": "bezirk:Südweststadt",
    "230": "bezirk:Südweststadt",
    "231": "bezirk:Südweststadt",
    "232": "bezirk:Südweststadt",
    "233": "bezirk:Südweststadt",
    "234": "bezirk:Südweststadt",
    "236": "bezirk:Nordweststadt",
    "237": "bezirk:Nordweststadt",
    "238": "bezirk:Nordweststadt",
    "239": "bezirk:Südstadt",
    "240": "bezirk:Südstadt",
    "241": "bezirk:Südstadt",
    "242": "bezirk:Oststadt",
    "243": "bezirk:Oststadt",
    "244": "bezirk:Weiherfeld-Dammerstock",
    "245": "bezirk:Weiherfeld-Dammerstock",
    "246": "bezirk:Weststadt",
    "247": "bezirk:Mühlburg",
    "248": "bezirk:Mühlburg",
    "249": "bezirk:Mühlburg",
    "250": "bezirk:Oststadt",
    "251": "bezirk:Weststadt",
    "252": "bezirk:Oststadt",
    "253": "bezirk:Oststadt",
    "254": "bezirk:Oststadt",
    "255": "bezirk:Oststadt",
    "256": "bezirk:Oststadt",
    "257": "bezirk:Oststadt",
    "258": "bezirk:Durlach",
    "259": "bezirk:Durlach",
    "260": "bezirk:Durlach",
    "261": "bezirk:Durlach",
    "262": "bezirk:Durlach",
    "263": "bezirk:Durlach",
    "264": "bezirk:Durlach",
    "265": "bezirk:Südweststadt",
    "266": "bezirk:Innenstadt-West",
    "267": "bezirk:Innenstadt-West",
    "268": "bezirk:Innenstadt-West",
    "269": "bezirk:Innenstadt-West",
    "270": "bezirk:Innenstadt-West",
    "273": "bezirk:Durlach",
    "274": "bezirk:Durlach",
    "279": "bezirk:Innenstadt-West",
    "280": "bezirk:Oststadt",
    "281": "bezirk:Innenstadt-Ost",
    "282": "bezirk:Innenstadt-West",
    "283": "bezirk:Südstadt",
    "284": "bezirk:Innenstadt-West",
    "286": "bezirk:Südstadt",
    "287": "bezirk:Südweststadt",
    "288": "bezirk:Südweststadt",
    "289": "bezirk:Südweststadt",
    "290": "bezirk:Südstadt",
    "291": "bezirk:Innenstadt-West",
    "292": "bezirk:Innenstadt-West",
    "293": "bezirk:Innenstadt-West",
    "294": "bezirk:Innenstadt-Ost",
  },
}

/** Zahl der Einheiten je Stadt, auch der stillen — der Nenner der Basisrate. */
export const UNIT_COUNTS: Readonly<Record<string, number>> = {
  "berlin": 103,
  "hamburg": 80,
  "frankfurt": 27,
  "muenchen": 82,
  "koeln": 45,
  "duesseldorf": 44,
  "karlsruhe": 13,
}

/** Die Einheit einer Zone, oder null, wenn die Stadt oder der Schlüssel unbekannt ist. */
export function unitOfZone(city: string, zoneKey: string): string | null {
  return ZONE_UNITS[city]?.[zoneKey] ?? null
}
