/**
 * ERZEUGT von `packages/ingest/src/build-zone-units.ts` — nicht von Hand ändern.
 *
 * Je Stadt: Zonenschlüssel → Einheit der Langzeitmuster. Eine Zone unter
 * 2 ha (Karlsruhes Stellplatzreihen, Hamburgs kleine Flächen) zählt für
 * ihren Bezirk, alle anderen für sich. `zone-units-aktuell.test.ts` hält
 * die Datei gegen die ausgelieferten Daten; der Befehl steht dort.
 */

export const ZONE_UNITS: Readonly<Record<string, Readonly<Record<string, string>>>> = {
  "berlin": {
    "1": "1",
    "2": "2",
    "3": "3",
    "4": "4",
    "5": "5",
    "6": "6",
    "7": "7",
    "8": "8",
    "10": "10",
    "11": "11",
    "12": "12",
    "13": "13",
    "14": "14",
    "15": "15",
    "16": "16",
    "18": "18",
    "19": "19",
    "20": "20",
    "21": "21",
    "22": "22",
    "23": "23",
    "24": "24",
    "25": "25",
    "26": "26",
    "27": "27",
    "28": "28",
    "29": "29",
    "30": "30",
    "33": "33",
    "34": "34",
    "35": "35",
    "36": "36",
    "37": "37",
    "38": "38",
    "40": "40",
    "42": "42",
    "43": "43",
    "44": "44",
    "45": "45",
    "46": "46",
    "49": "49",
    "50": "50",
    "54": "54",
    "55": "55",
    "60": "60",
    "61": "61",
    "63": "63",
    "64": "64",
    "65": "65",
    "66": "66",
    "67": "67",
    "68": "68",
    "69": "69",
    "70": "70",
    "71": "71",
    "72": "72",
    "73": "73",
    "74": "74",
    "75": "75",
    "76": "76",
    "77": "77",
    "78": "78",
    "79": "79",
    "80": "80",
    "81": "81",
    "82": "82",
    "83": "83",
    "84": "84",
    "85": "85",
    "86": "86",
    "87": "87",
    "88": "88",
    "89": "89",
    "90": "90",
    "91": "91",
    "92": "92",
    "100": "100",
    "101": "101",
    "105": "105",
    "106": "106",
    "120": "120",
    "121": "121",
    "126": "126",
    "127": "127",
    "128": "128",
    "129": "129",
    "130": "130",
    "131": "131",
    "132": "132",
    "133": "133",
    "134": "134",
    "135": "135",
    "136": "136",
    "137": "137",
    "138": "138",
    "17-CW": "17-CW",
    "17-TS": "17-TS",
    "41-Mitte": "41-Mitte",
    "41-Pankow": "41-Pankow",
    "51-Arena Süd": "51-Arena Süd",
    "51-OberbaumCity": "51-OberbaumCity",
    "9-CW": "9-CW",
    "9-TS": "9-TS",
  },
  "hamburg": {
    "A100": "A100",
    "A101": "A101",
    "A102": "A102",
    "A103": "A103",
    "A104": "A104",
    "A105": "A105",
    "A106": "A106",
    "A107": "A107",
    "A108": "A108",
    "A109": "A109",
    "A110": "A110",
    "AE100": "AE100",
    "AE101": "AE101",
    "AE102": "AE102",
    "AE103": "AE103",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32004": "bezirk:Rotherbaum",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32005": "DE.HH.UP_BEWOHNERPARKGEBIETE_32005",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32006": "bezirk:Rotherbaum",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32007": "bezirk:Rotherbaum",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32008": "bezirk:Ottensen",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32009": "bezirk:Ottensen",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32011": "bezirk:Ottensen",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32012": "bezirk:Altona-Altstadt",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32013": "bezirk:Ottensen",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32015": "bezirk:Altona-Altstadt",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32017": "bezirk:Altona-Altstadt",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32018": "bezirk:Ottensen",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32019": "bezirk:Altona-Altstadt",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32020": "bezirk:Ottensen",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32022": "bezirk:Altona-Altstadt",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32023": "bezirk:Altona-Nord",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32028": "DE.HH.UP_BEWOHNERPARKGEBIETE_32028",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32029": "bezirk:St. Georg",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32030": "bezirk:St. Georg",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32031": "bezirk:St. Georg",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32032": "bezirk:St. Georg",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32033": "bezirk:St. Georg",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32034": "bezirk:Hammerbrook",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32035": "bezirk:Altona-Altstadt",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32039": "bezirk:St. Pauli",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32045": "bezirk:St. Georg",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32046": "bezirk:Hammerbrook",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32047": "bezirk:Hammerbrook",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32052": "bezirk:Harvestehude",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32053": "bezirk:Harvestehude",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32061": "DE.HH.UP_BEWOHNERPARKGEBIETE_32061",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32063": "bezirk:Lokstedt",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32069": "bezirk:Eimsbüttel",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32076": "bezirk:Eppendorf",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32078": "bezirk:Eppendorf",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32082": "bezirk:Lokstedt",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32084": "bezirk:Lokstedt",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32086": "DE.HH.UP_BEWOHNERPARKGEBIETE_32086",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32087": "bezirk:Hoheluft-Ost",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32088": "bezirk:Eppendorf",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32089": "bezirk:Eppendorf",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32106": "DE.HH.UP_BEWOHNERPARKGEBIETE_32106",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32107": "bezirk:Uhlenhorst",
    "DE.HH.UP_BEWOHNERPARKGEBIETE_32108": "bezirk:Uhlenhorst",
    "E300": "E300",
    "E301": "E301",
    "E302": "E302",
    "E303": "E303",
    "E304": "E304",
    "E305": "E305",
    "E306": "E306",
    "E307": "E307",
    "E308": "E308",
    "E309": "E309",
    "E310": "E310",
    "E311": "E311",
    "E312": "E312",
    "E313": "E313",
    "E314": "E314",
    "E315": "E315",
    "E316": "E316",
    "M100": "M100",
    "M101": "M101",
    "M102": "M102",
    "M103": "M103",
    "M104": "M104",
    "M105": "M105",
    "M106": "M106",
    "M107": "M107",
    "M108": "M108",
    "M109": "M109",
    "M110": "M110",
    "M111": "M111",
    "MA201": "MA201",
    "MA202": "MA202",
    "MA203": "MA203",
    "MA204": "MA204",
    "N100": "N100",
    "N101": "N101",
    "N102": "N102",
    "N103": "N103",
    "N104": "N104",
    "N105": "N105",
    "N106": "N106",
    "N107": "N107",
    "N108": "N108",
    "N109": "N109",
    "N110": "N110",
    "N111": "N111",
    "N112": "N112",
    "N113": "N113",
  },
  "frankfurt": {
    "0": "0",
    "4": "4",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "10": "10",
    "12": "12",
    "13": "13",
    "15": "15",
    "16": "16",
    "17": "17",
    "18": "18",
    "19": "19",
    "20": "20",
    "21": "21",
    "22": "22",
    "25": "25",
    "26": "26",
    "29": "29",
    "31": "31",
    "32": "32",
    "35": "35",
    "38": "38",
    "39": "39",
    "40": "40",
    "41": "41",
  },
  "muenchen": {
    "Akademieviertel": "Akademieviertel",
    "Albrechtstraße": "Albrechtstraße",
    "Alte Heide": "Alte Heide",
    "Alter Südfriedhof": "Alter Südfriedhof",
    "Altschwabing": "Altschwabing",
    "Altstadt": "Altstadt",
    "Apostelblöcke": "Apostelblöcke",
    "Barbarastraße": "Barbarastraße",
    "Bayernplatz": "Bayernplatz",
    "Biederstein": "Biederstein",
    "Borstei": "Borstei",
    "Brudermühlviertel": "Brudermühlviertel",
    "Clemensstraße": "Clemensstraße",
    "Domagpark": "Domagpark",
    "Dreimühlenviertel": "Dreimühlenviertel",
    "Ebenau": "Ebenau",
    "Eichendorffplatz": "Eichendorffplatz",
    "Franziskanerstraße": "Franziskanerstraße",
    "Franzosenviertel": "Franzosenviertel",
    "Freiham": "Freiham",
    "Gärtnerplatz": "Gärtnerplatz",
    "Giesinger Bahnhof": "Giesinger Bahnhof",
    "Giselastraße": "Giselastraße",
    "Glockenbachviertel": "Glockenbachviertel",
    "Grillparzerstraße": "Grillparzerstraße",
    "Hauptbahnhof": "Hauptbahnhof",
    "Herzog-Ernst-Platz": "Herzog-Ernst-Platz",
    "Heßstraße": "Heßstraße",
    "Innenstadtklinikum": "Innenstadtklinikum",
    "Karolinenplatz": "Karolinenplatz",
    "Karwendelstraße": "Karwendelstraße",
    "Kasernenviertel": "Kasernenviertel",
    "Kirchenstraße": "Kirchenstraße",
    "Klinikviertel": "Klinikviertel",
    "Kölner Platz": "Kölner Platz",
    "Königsplatz": "Königsplatz",
    "Lerchenauer Straße": "Lerchenauer Straße",
    "Lindwurmstraße": "Lindwurmstraße",
    "Margaretenplatz": "Margaretenplatz",
    "Marsfeld": "Marsfeld",
    "Messestadt": "Messestadt",
    "Mittleres Lehel": "Mittleres Lehel",
    "Nördliche Au": "Nördliche Au",
    "Nördliche Passauerstraße": "Nördliche Passauerstraße",
    "Nördliches Lehel": "Nördliches Lehel",
    "Partnachplatz": "Partnachplatz",
    "Pasing Süd": "Pasing Süd",
    "Pinakotheken": "Pinakotheken",
    "Potsdamer Straße": "Potsdamer Straße",
    "Regerplatz": "Regerplatz",
    "Ridlerstraße": "Ridlerstraße",
    "Rotkreuzplatz Nord": "Rotkreuzplatz Nord",
    "Rotkreuzplatz Süd": "Rotkreuzplatz Süd",
    "Schleißheimer Straße": "Schleißheimer Straße",
    "Schönfeldviertel": "Schönfeldviertel",
    "Schönstraße Nord": "Schönstraße Nord",
    "Schönstraße Süd": "Schönstraße Süd",
    "Schwabing Mitte": "Schwabing Mitte",
    "Schwanthalerhöhe": "Schwanthalerhöhe",
    "Schyrenbad": "Schyrenbad",
    "Seydlitzplatz": "Seydlitzplatz",
    "Silberhornstr.": "Silberhornstr.",
    "St.-Benno-Viertel": "St.-Benno-Viertel",
    "St.-Martins-Platz": "St.-Martins-Platz",
    "St.-Pauls-Viertel": "St.-Pauls-Viertel",
    "St.-Vinzenz-Viertel": "St.-Vinzenz-Viertel",
    "Südliche Au": "Südliche Au",
    "Südliche Hansastraße": "Südliche Hansastraße",
    "Südliches Lehel": "Südliches Lehel",
    "Tegernseer Landstr.": "Tegernseer Landstr.",
    "Thalkirchen": "Thalkirchen",
    "Theresienhöhe": "Theresienhöhe",
    "Tristanstraße": "Tristanstraße",
    "TU-Viertel": "TU-Viertel",
    "Untergiesing": "Untergiesing",
    "Untersendling": "Untersendling",
    "Volkartstraße": "Volkartstraße",
    "Walchenseeplatz": "Walchenseeplatz",
    "West Schwabing": "West Schwabing",
    "Westend": "Westend",
    "Wettersteinplatz": "Wettersteinplatz",
    "Winzererstraße": "Winzererstraße",
  },
  "koeln": {
    "Agnesviertel I": "Agnesviertel I",
    "Agnesviertel II": "Agnesviertel II",
    "Belgisches Viertel": "Belgisches Viertel",
    "City-Martinsviertel": "City-Martinsviertel",
    "Deutz I": "Deutz I",
    "Deutz II": "Deutz II",
    "Deutz III": "Deutz III",
    "Deutz V": "Deutz V",
    "Ehrenfeld I": "Ehrenfeld I",
    "Ehrenfeld II": "Ehrenfeld II",
    "Ehrenfeld III": "Ehrenfeld III",
    "Ehrenfeld IV": "Ehrenfeld IV",
    "Eigelstein": "Eigelstein",
    "Georgsviertel": "Georgsviertel",
    "Gereonsviertel": "Gereonsviertel",
    "Griechenmarktviertel": "Griechenmarktviertel",
    "Hohenlind": "Hohenlind",
    "Hültzviertel": "Hültzviertel",
    "Kalk": "Kalk",
    "Keupstr.": "Keupstr.",
    "Kunibertsviertel": "Kunibertsviertel",
    "Lindenthal-Nord I": "Lindenthal-Nord I",
    "Lindenthal-Nord II": "Lindenthal-Nord II",
    "Lindenthal-Süd I": "Lindenthal-Süd I",
    "Lindenthal-Süd II": "Lindenthal-Süd II",
    "Mülheim": "Mülheim",
    "Nippes": "Nippes",
    "Nippes EAW": "Nippes EAW",
    "Nippes I": "Nippes I",
    "Nippes II": "Nippes II",
    "Nippes III": "Nippes III",
    "Nippes IV": "Nippes IV",
    "Nördlich Neumarkt": "Nördlich Neumarkt",
    "Nördliche Neustadt": "Nördliche Neustadt",
    "Pantaleonsviertel": "Pantaleonsviertel",
    "Porz-City": "Porz-City",
    "Rathenauviertel": "Rathenauviertel",
    "Severinsviertel": "Severinsviertel",
    "Südbahnhof": "Südbahnhof",
    "Südliche Neustadt I": "Südliche Neustadt I",
    "Südliche Neustadt II": "Südliche Neustadt II",
    "Sülz-Nord I": "Sülz-Nord I",
    "Sülz-Nord II": "Sülz-Nord II",
    "Weiden Nord": "Weiden Nord",
    "Weiden Süd": "Weiden Süd",
  },
  "duesseldorf": {
    "Ahnfeldstraße (AS)": "Ahnfeldstraße (AS)",
    "Altstadt - Nord (K)": "Altstadt - Nord (K)",
    "Altstadt (A)": "Altstadt (A)",
    "Blücherstraße (S)": "Blücherstraße (S)",
    "Christophstraße (CH)": "Christophstraße (CH)",
    "Daimler (B)": "Daimler (B)",
    "Derendorf (Q)": "Derendorf (Q)",
    "Derendorfer Straße (W)": "Derendorfer Straße (W)",
    "Feldstraße (H)": "Feldstraße (H)",
    "Feuerbachstraße (FB)": "Feuerbachstraße (FB)",
    "Flughafen (F)": "Flughafen (F)",
    "Friedrichstadt (N)": "Friedrichstadt (N)",
    "Gerresheimer Straße (GS)": "Gerresheimer Straße (GS)",
    "Golzheim - Rolandstraße (C)": "Golzheim - Rolandstraße (C)",
    "Golzheimer Platz (GP)": "Golzheimer Platz (GP)",
    "Hasselsstraße (X)": "bezirk:Hassels",
    "Hauptbahnhof - Ost (HO)": "Hauptbahnhof - Ost (HO)",
    "Henkelgebiet (M)": "Henkelgebiet (M)",
    "Hermannplatz (HP)": "Hermannplatz (HP)",
    "Immermannstraße (O)": "Immermannstraße (O)",
    "Inselstraße (J)": "Inselstraße (J)",
    "Kaiserswerth (V)": "Kaiserswerth (V)",
    "Kanzlerstraße (T)": "Kanzlerstraße (T)",
    "Klosterstraße (L)": "Klosterstraße (L)",
    "Lessingplatz (LP)": "Lessingplatz (LP)",
    "Lichtenbroich (LB)": "Lichtenbroich (LB)",
    "Moorenplatz (MP)": "Moorenplatz (MP)",
    "Moorenstraße (MS)": "Moorenstraße (MS)",
    "Münsterstraße (MÜ)": "Münsterstraße (MÜ)",
    "Neuwerker-, Viersener Straße (NV)": "Neuwerker-, Viersener Straße (NV)",
    "Niederkassel (NK)": "Niederkassel (NK)",
    "Oberkassel - Ost (OK)": "Oberkassel - Ost (OK)",
    "Oberkassel - West (Z)": "Oberkassel - West (Z)",
    "Pempelforter Straße (P)": "Pempelforter Straße (P)",
    "Reeser Platz (RP)": "Reeser Platz (RP)",
    "Schanzenstraße (SC)": "Schanzenstraße (SC)",
    "Schillerplatz (SP)": "Schillerplatz (SP)",
    "Stockum - Blumenviertel (U)": "Stockum - Blumenviertel (U)",
    "Unterbilk (R)": "Unterbilk (R)",
    "Unterrath - Ost (D)": "Unterrath - Ost (D)",
    "Unterrath - West (E)": "Unterrath - West (E)",
    "Unterrath (UR)": "Unterrath (UR)",
    "Venloer Straße (G)": "Venloer Straße (G)",
    "Wersten - Düsseldörfchen (Y)": "Wersten - Düsseldörfchen (Y)",
  },
  "karlsruhe": {
    "1": "bezirk:Durlach",
    "2": "bezirk:Innenstadt-West",
    "4": "bezirk:Südweststadt",
    "5": "bezirk:Durlach",
    "6": "bezirk:Südweststadt",
    "7": "bezirk:Innenstadt-West",
    "8": "bezirk:Innenstadt-West",
    "9": "bezirk:Innenstadt-West",
    "10": "bezirk:Innenstadt-West",
    "11": "bezirk:Innenstadt-West",
    "12": "bezirk:Innenstadt-West",
    "13": "bezirk:Innenstadt-West",
    "14": "bezirk:Südweststadt",
    "15": "bezirk:Innenstadt-Ost",
    "16": "bezirk:Innenstadt-Ost",
    "17": "bezirk:Südstadt",
    "18": "bezirk:Oststadt",
    "19": "bezirk:Mühlburg",
    "20": "bezirk:Südweststadt",
    "21": "bezirk:Südweststadt",
    "22": "bezirk:Südweststadt",
    "23": "bezirk:Rüppurr",
    "24": "bezirk:Südweststadt",
    "25": "bezirk:Innenstadt-West",
    "26": "bezirk:Innenstadt-West",
    "27": "bezirk:Innenstadt-West",
    "28": "bezirk:Innenstadt-West",
    "29": "bezirk:Innenstadt-West",
    "30": "bezirk:Südweststadt",
    "31": "bezirk:Südweststadt",
    "32": "bezirk:Südweststadt",
    "33": "bezirk:Durlach",
    "34": "bezirk:Durlach",
    "35": "bezirk:Durlach",
    "36": "bezirk:Durlach",
    "37": "bezirk:Südweststadt",
    "38": "bezirk:Südweststadt",
    "39": "bezirk:Südweststadt",
    "40": "bezirk:Südweststadt",
    "41": "bezirk:Südweststadt",
    "42": "bezirk:Südstadt",
    "43": "bezirk:Südstadt",
    "44": "bezirk:Innenstadt-West",
    "45": "bezirk:Mühlburg",
    "46": "bezirk:Oststadt",
    "47": "bezirk:Mühlburg",
    "48": "bezirk:Innenstadt-Ost",
    "49": "bezirk:Durlach",
    "50": "bezirk:Weststadt",
    "51": "bezirk:Durlach",
    "52": "bezirk:Durlach",
    "53": "bezirk:Durlach",
    "54": "bezirk:Oststadt",
    "55": "bezirk:Oststadt",
    "57": "bezirk:Innenstadt-Ost",
    "58": "bezirk:Innenstadt-Ost",
    "59": "bezirk:Südweststadt",
    "60": "bezirk:Oststadt",
    "61": "bezirk:Südweststadt",
    "62": "bezirk:Innenstadt-West",
    "63": "bezirk:Mühlburg",
    "64": "bezirk:Innenstadt-West",
    "65": "bezirk:Innenstadt-Ost",
    "66": "bezirk:Innenstadt-West",
    "67": "bezirk:Innenstadt-West",
    "68": "bezirk:Innenstadt-West",
    "69": "bezirk:Innenstadt-Ost",
    "70": "bezirk:Innenstadt-Ost",
    "71": "bezirk:Innenstadt-West",
    "72": "bezirk:Innenstadt-West",
    "73": "bezirk:Innenstadt-West",
    "74": "bezirk:Innenstadt-West",
    "75": "bezirk:Innenstadt-West",
    "76": "bezirk:Innenstadt-West",
    "77": "bezirk:Oberreut",
    "78": "bezirk:Innenstadt-West",
    "79": "bezirk:Weststadt",
    "80": "bezirk:Innenstadt-West",
    "81": "bezirk:Innenstadt-West",
    "82": "bezirk:Innenstadt-West",
    "83": "bezirk:Südweststadt",
    "84": "bezirk:Oststadt",
    "85": "bezirk:Durlach",
    "86": "bezirk:Südweststadt",
    "87": "bezirk:Südweststadt",
    "88": "bezirk:Südweststadt",
    "89": "bezirk:Südweststadt",
    "90": "bezirk:Südweststadt",
    "91": "bezirk:Südweststadt",
    "92": "bezirk:Weststadt",
    "93": "bezirk:Weststadt",
    "94": "bezirk:Innenstadt-Ost",
    "95": "bezirk:Südweststadt",
    "96": "bezirk:Innenstadt-West",
    "97": "bezirk:Innenstadt-West",
    "98": "bezirk:Südweststadt",
    "99": "bezirk:Südweststadt",
    "100": "bezirk:Innenstadt-West",
    "101": "bezirk:Innenstadt-West",
    "102": "bezirk:Nordweststadt",
    "103": "bezirk:Nordweststadt",
    "104": "bezirk:Südweststadt",
    "105": "bezirk:Mühlburg",
    "106": "bezirk:Innenstadt-West",
    "107": "bezirk:Weststadt",
    "108": "bezirk:Weststadt",
    "109": "bezirk:Weststadt",
    "110": "bezirk:Südstadt",
    "112": "bezirk:Innenstadt-Ost",
    "113": "bezirk:Durlach",
    "114": "bezirk:Südweststadt",
    "115": "bezirk:Südweststadt",
    "116": "bezirk:Innenstadt-West",
    "117": "bezirk:Durlach",
    "118": "bezirk:Durlach",
    "119": "bezirk:Innenstadt-West",
    "121": "bezirk:Weststadt",
    "122": "bezirk:Südweststadt",
    "123": "bezirk:Rüppurr",
    "124": "bezirk:Mühlburg",
    "125": "bezirk:Innenstadt-West",
    "126": "bezirk:Weststadt",
    "127": "bezirk:Südweststadt",
    "128": "bezirk:Innenstadt-West",
    "129": "bezirk:Innenstadt-West",
    "131": "bezirk:Südstadt",
    "132": "bezirk:Innenstadt-West",
    "133": "bezirk:Innenstadt-West",
    "134": "bezirk:Innenstadt-West",
    "135": "bezirk:Innenstadt-Ost",
    "136": "bezirk:Innenstadt-West",
    "137": "bezirk:Innenstadt-West",
    "138": "bezirk:Innenstadt-West",
    "139": "bezirk:Innenstadt-West",
    "140": "bezirk:Innenstadt-West",
    "141": "bezirk:Innenstadt-West",
    "142": "bezirk:Innenstadt-Ost",
    "143": "bezirk:Innenstadt-West",
    "144": "bezirk:Südweststadt",
    "146": "bezirk:Südweststadt",
    "147": "bezirk:Südweststadt",
    "148": "bezirk:Durlach",
    "149": "bezirk:Innenstadt-West",
    "150": "bezirk:Weststadt",
    "151": "bezirk:Südstadt",
    "152": "bezirk:Südstadt",
    "153": "bezirk:Südstadt",
    "154": "bezirk:Südstadt",
    "155": "bezirk:Südweststadt",
    "156": "bezirk:Südweststadt",
    "157": "bezirk:Nordstadt",
    "158": "bezirk:Mühlburg",
    "159": "bezirk:Mühlburg",
    "160": "bezirk:Innenstadt-Ost",
    "161": "bezirk:Innenstadt-West",
    "162": "bezirk:Weststadt",
    "163": "bezirk:Südweststadt",
    "164": "bezirk:Südstadt",
    "165": "bezirk:Durlach",
    "166": "bezirk:Durlach",
    "167": "bezirk:Südweststadt",
    "169": "bezirk:Durlach",
    "170": "bezirk:Mühlburg",
    "171": "bezirk:Oststadt",
    "172": "bezirk:Innenstadt-Ost",
    "173": "bezirk:Südweststadt",
    "174": "bezirk:Weststadt",
    "175": "bezirk:Innenstadt-West",
    "176": "bezirk:Südweststadt",
    "177": "bezirk:Innenstadt-West",
    "178": "bezirk:Weststadt",
    "179": "bezirk:Innenstadt-Ost",
    "180": "bezirk:Innenstadt-West",
    "181": "bezirk:Weststadt",
    "182": "bezirk:Nordweststadt",
    "183": "bezirk:Nordweststadt",
    "184": "bezirk:Nordweststadt",
    "185": "bezirk:Nordweststadt",
    "186": "bezirk:Südweststadt",
    "187": "bezirk:Südweststadt",
    "188": "bezirk:Südweststadt",
    "189": "bezirk:Südweststadt",
    "190": "bezirk:Südweststadt",
    "191": "bezirk:Südweststadt",
    "192": "bezirk:Südweststadt",
    "193": "bezirk:Südweststadt",
    "194": "bezirk:Weststadt",
    "195": "bezirk:Oststadt",
    "196": "bezirk:Innenstadt-West",
    "197": "bezirk:Innenstadt-West",
    "198": "bezirk:Innenstadt-West",
    "199": "bezirk:Weststadt",
    "200": "bezirk:Innenstadt-West",
    "201": "bezirk:Südweststadt",
    "202": "bezirk:Südweststadt",
    "203": "bezirk:Südstadt",
    "204": "bezirk:Innenstadt-Ost",
    "205": "bezirk:Mühlburg",
    "206": "bezirk:Südweststadt",
    "207": "bezirk:Südstadt",
    "208": "bezirk:Innenstadt-West",
    "209": "bezirk:Weststadt",
    "210": "bezirk:Oststadt",
    "211": "bezirk:Oststadt",
    "212": "bezirk:Oststadt",
    "213": "bezirk:Oststadt",
    "214": "bezirk:Oststadt",
    "215": "bezirk:Oststadt",
    "216": "bezirk:Oststadt",
    "217": "bezirk:Oststadt",
    "218": "bezirk:Oststadt",
    "219": "bezirk:Oststadt",
    "220": "bezirk:Oststadt",
    "221": "bezirk:Durlach",
    "222": "bezirk:Südstadt",
    "223": "bezirk:Innenstadt-West",
    "224": "bezirk:Innenstadt-West",
    "225": "bezirk:Innenstadt-West",
    "226": "bezirk:Innenstadt-West",
    "227": "bezirk:Innenstadt-West",
    "228": "bezirk:Innenstadt-Ost",
    "229": "bezirk:Südweststadt",
    "230": "bezirk:Südweststadt",
    "231": "bezirk:Südweststadt",
    "232": "bezirk:Südweststadt",
    "233": "bezirk:Südweststadt",
    "234": "bezirk:Südweststadt",
    "236": "bezirk:Nordweststadt",
    "237": "bezirk:Nordweststadt",
    "238": "bezirk:Nordweststadt",
    "239": "bezirk:Südstadt",
    "240": "bezirk:Südstadt",
    "241": "bezirk:Südstadt",
    "242": "bezirk:Oststadt",
    "243": "bezirk:Oststadt",
    "244": "bezirk:Weiherfeld-Dammerstock",
    "245": "bezirk:Weiherfeld-Dammerstock",
    "246": "bezirk:Weststadt",
    "247": "bezirk:Mühlburg",
    "248": "bezirk:Mühlburg",
    "249": "bezirk:Mühlburg",
    "250": "bezirk:Oststadt",
    "251": "bezirk:Weststadt",
    "252": "bezirk:Oststadt",
    "253": "bezirk:Oststadt",
    "254": "bezirk:Oststadt",
    "255": "bezirk:Oststadt",
    "256": "bezirk:Oststadt",
    "257": "bezirk:Oststadt",
    "258": "bezirk:Durlach",
    "259": "bezirk:Durlach",
    "260": "bezirk:Durlach",
    "261": "bezirk:Durlach",
    "262": "bezirk:Durlach",
    "263": "bezirk:Durlach",
    "264": "bezirk:Durlach",
    "265": "bezirk:Südweststadt",
    "266": "bezirk:Innenstadt-West",
    "267": "bezirk:Innenstadt-West",
    "268": "bezirk:Innenstadt-West",
    "269": "bezirk:Innenstadt-West",
    "270": "bezirk:Innenstadt-West",
    "273": "bezirk:Durlach",
    "274": "bezirk:Durlach",
    "279": "bezirk:Innenstadt-West",
    "280": "bezirk:Oststadt",
    "281": "bezirk:Innenstadt-Ost",
    "282": "bezirk:Innenstadt-West",
    "283": "bezirk:Südstadt",
    "284": "bezirk:Innenstadt-West",
    "286": "bezirk:Südstadt",
    "287": "bezirk:Südweststadt",
    "288": "bezirk:Südweststadt",
    "289": "bezirk:Südweststadt",
    "290": "bezirk:Südstadt",
    "291": "bezirk:Innenstadt-West",
    "292": "bezirk:Innenstadt-West",
    "293": "bezirk:Innenstadt-West",
    "294": "bezirk:Innenstadt-Ost",
  },
  "freiburg": {
    "1 (Fläche 7)": "1 (Fläche 7)",
    "2 (Fläche 5)": "2 (Fläche 5)",
    "2 (Fläche 6)": "2 (Fläche 6)",
    "3 (Fläche 10)": "bezirk:Stühlinger",
    "3 (Fläche 12)": "bezirk:Betzenhausen",
    "3 (Fläche 13)": "bezirk:Lehen",
    "3 (Fläche 14)": "bezirk:Landwasser",
    "3 (Fläche 15)": "bezirk:Zähringen",
    "3 (Fläche 16)": "bezirk:St. Georgen",
    "3 (Fläche 17)": "bezirk:St. Georgen",
    "3 (Fläche 18)": "bezirk:Waldsee",
    "3 (Fläche 19)": "bezirk:Waldsee",
    "3 (Fläche 20)": "bezirk:Littenweiler",
    "3 (Fläche 21)": "bezirk:Littenweiler",
    "3 (Fläche 22)": "bezirk:Littenweiler",
    "3 (Fläche 23)": "bezirk:Wiehre",
    "3 (Fläche 24)": "bezirk:Haslach",
    "3 (Fläche 25)": "bezirk:Haslach",
    "3 (Fläche 26)": "bezirk:Brühl",
    "3 (Fläche 27)": "bezirk:Stühlinger",
    "3 (Fläche 28)": "bezirk:St. Georgen",
    "3 (Fläche 29)": "bezirk:St. Georgen",
    "3 (Fläche 30)": "bezirk:St. Georgen",
    "3 (Fläche 31)": "bezirk:St. Georgen",
    "3 (Fläche 32)": "bezirk:Wiehre",
    "3 (Fläche 35)": "3 (Fläche 35)",
    "3 (Fläche 36)": "bezirk:Zähringen",
    "3 (Fläche 37)": "bezirk:Zähringen",
    "3 (Fläche 38)": "bezirk:Zähringen",
    "3 (Fläche 39)": "bezirk:Zähringen",
    "3 (Fläche 40)": "3 (Fläche 40)",
    "3 (Fläche 41)": "3 (Fläche 41)",
    "3 (Fläche 42)": "3 (Fläche 42)",
    "3 (Fläche 43)": "3 (Fläche 43)",
    "3 (Fläche 44)": "3 (Fläche 44)",
    "3 (Fläche 45)": "3 (Fläche 45)",
    "3 (Fläche 9)": "bezirk:Stühlinger",
  },
  "cottbus": {
    "II": "II",
    "III": "III",
    "IV": "IV",
    "V": "V",
    "VI": "VI",
  },
  "rostock": {
    "A1": "A1",
    "A2": "A2",
    "A3": "A3",
    "A4": "A4",
    "B1": "B1",
    "B2": "B2",
    "H1": "H1",
    "W1": "W1",
    "W2": "W2",
    "W4": "bezirk:Seebad Warnemünde",
  },
  "schwerin": {
    "A": "A",
    "A/D": "bezirk:Schelfstadt",
    "A/F": "A/F",
    "C": "C",
    "D": "D",
    "F": "F",
    "G": "G",
    "H": "H",
    "J": "J",
    "O": "O",
  },
  "graz": {
    "10": "10",
    "11": "11",
    "01": "01",
    "02": "02",
    "03": "03",
    "05": "05",
    "06": "06",
    "07": "07",
    "08": "08",
    "09": "09",
    "A": "A",
    "B": "B",
    "C": "C",
    "D": "D",
    "E": "E",
    "F": "F",
    "G": "G",
    "H": "H",
    "I": "I",
    "J": "J",
    "S": "bezirk:St. Peter",
    "S1": "bezirk:Lend",
    "S2": "bezirk:Lend",
    "S3": "bezirk:Puntigam",
  },
  "salzburg": {
    "189": "189",
    "190": "190",
    "193": "193",
    "194": "194",
    "195": "bezirk:Nonntal",
    "199": "bezirk:Maxglan",
    "200": "bezirk:Maxglan",
    "204": "204",
    "205": "bezirk:Elisabeth Vorstadt",
    "222": "222",
    "321": "321",
    "322": "322",
    "402": "402",
    "403": "403",
    "404": "404",
    "405": "405",
    "441": "441",
    "463": "463",
    "464": "464",
    "466": "466",
    "468": "468",
    "469": "469",
    "470": "470",
    "471": "471",
    "483": "483",
    "502": "502",
    "503": "503",
    "504": "bezirk:Itzling",
    "521": "bezirk:Parsch",
    "542": "542",
    "544": "544",
    "547": "547",
    "548": "548",
    "563": "563",
    "582": "bezirk:Riedenburg",
    "584": "584",
    "585": "585",
    "604": "604",
    "605": "bezirk:Maxglan",
    "641": "641",
  },
  "innsbruck": {
    "132": "bezirk:Hötting",
    "133": "bezirk:Hötting West",
    "134": "134",
    "135": "bezirk:Amras",
    "136": "136",
    "137": "bezirk:Hötting West",
    "138": "138",
    "139": "139",
    "140": "140",
    "141": "141",
    "142": "142",
    "143": "143",
    "144": "144",
    "145": "145",
    "146": "146",
    "147": "147",
    "148": "148",
    "149": "149",
    "150": "150",
    "151": "151",
    "152": "152",
  },
  "bern": {
    "3000": "3000",
    "3003": "3003",
    "3004": "3004",
    "3005": "3005",
    "3006": "3006",
    "3011": "3011",
    "3012": "3012",
    "3013": "3013",
    "3014": "3014",
    "3018": "3018",
    "3027": "3027",
    "3004/1": "3004/1",
    "3004/2": "3004/2",
    "3004/3": "bezirk:Felsenau",
    "3006/1": "3006/1",
    "3006/2": "3006/2",
    "3006/3": "3006/3",
    "3006/4": "3006/4",
    "3006/5": "3006/5",
    "3006/6": "3006/6",
    "3007/1": "3007/1",
    "3007/2": "3007/2",
    "3007/3": "3007/3",
    "3007/4": "3007/4",
    "3008/1": "3008/1",
    "3008/2": "3008/2",
    "3008/3": "3008/3",
    "3014/1": "3014/1",
    "3018/11": "3018/11",
    "3027/2": "3027/2",
    "3027/3": "3027/3",
  },
  "zuerich": {
    "Innenstadt": "Innenstadt",
    "Oerlikon": "Oerlikon",
  },
  "wien": {
    "1": "1",
    "2": "2",
    "3": "3",
    "6": "6",
    "7": "7",
    "8": "8",
    "9": "9",
    "10": "10",
    "11": "11",
    "12": "12",
    "13": "13",
    "14": "14",
    "15": "15",
    "16": "16",
    "17": "17",
    "18": "18",
    "19": "19",
    "20": "20",
    "21": "21",
    "22": "22",
    "23": "23",
    "14+15": "14+15",
    "4+5": "4+5",
    "Alser Straße 17 bis 21": "bezirk:Josefstadt",
    "Alser Straße 23 bis 29": "bezirk:Josefstadt",
    "Alser Straße 24 bis 28": "bezirk:Alsergrund",
    "Alser Straße 34": "bezirk:Alsergrund",
    "Alser Straße 39 bis 47": "bezirk:Josefstadt",
    "Alser Straße 46 bis 48": "bezirk:Alsergrund",
    "Alser Straße 51 bis 61": "bezirk:Josefstadt",
    "Alser Straße 63A bis 65": "bezirk:Josefstadt",
    "Alser Straße 67 bis 69": "bezirk:Josefstadt",
    "Alser Straße 8 bis 16": "bezirk:Alsergrund",
    "Alser Straße ggü. 55 bis ggü. 61": "bezirk:Josefstadt",
    "Am Spitz 1": "bezirk:Floridsdorf",
    "Am Spitz 11 bis 12": "bezirk:Floridsdorf",
    "Am Spitz 9 bis 10": "bezirk:Floridsdorf",
    "Am Spitz ggü. 11 bis ggü. 12": "bezirk:Floridsdorf",
    "Angerer Straße 2 bis 4": "bezirk:Floridsdorf",
    "Angerer Straße 5 bis 5B": "bezirk:Floridsdorf",
    "Anton-Baumgartner-Straße 129 bis 131": "bezirk:Liesing",
    "Anton-Baumgartner-Straße ggü. 129 bis ggü. 131": "bezirk:Liesing",
    "Arndtstraße 37 bis 39": "bezirk:Meidling",
    "Arndtstraße 42": "bezirk:Meidling",
    "Aspernbrückengasse 1": "bezirk:Leopoldstadt",
    "Austerlitzgasse 1 ggü. Stiege 3": "bezirk:Donaustadt",
    "Billrothstraße 19 bis 21": "bezirk:Döbling",
    "Billrothstraße 23 bis 31": "bezirk:Döbling",
    "Billrothstraße 24 bis 26-30": "bezirk:Döbling",
    "Billrothstraße 40 bis 42": "bezirk:Döbling",
    "Billrothstraße 43 bis 49": "bezirk:Döbling",
    "Billrothstraße 55 bis 63": "bezirk:Döbling",
    "Billrothstraße 8 bis 18": "bezirk:Döbling",
    "Billrothstraße 83A bis 85": "bezirk:Döbling",
    "Billrothstraße ggü 83A bis 85": "bezirk:Döbling",
    "Breitenfurter Straße 230 Stiege 3 bis 238": "bezirk:Liesing",
    "Breitenfurter Straße 246 bis 248": "bezirk:Liesing",
    "Breitenfurter Straße 254 bis 258": "bezirk:Liesing",
    "Breitenfurter Straße 281 bis 281A": "bezirk:Liesing",
    "Breitenfurter Straße 291-297": "bezirk:Liesing",
    "Breitenfurter Straße 324": "bezirk:Liesing",
    "Breitenfurter Straße 338 bis 342": "bezirk:Liesing",
    "Breitenfurter Straße 359 bis 365": "bezirk:Liesing",
    "Breitenfurter Straße 360-368": "bezirk:Liesing",
    "Breitenfurter Straße 381A bis 389": "bezirk:Liesing",
    "Breitenfurter Straße ggü. 360 - 368": "bezirk:Liesing",
    "Brünner Straße 2-4 bis 10": "bezirk:Floridsdorf",
    "Brünner Straße 20 bis 22": "bezirk:Floridsdorf",
    "Brünner Straße 26-32": "bezirk:Floridsdorf",
    "Brünner Straße 29 bis 31": "bezirk:Floridsdorf",
    "Brünner Straße 9 bis 17": "bezirk:Floridsdorf",
    "Buchengasse 77 bis 79": "bezirk:Favoriten",
    "Cobenzlgasse ggü. 10": "bezirk:Döbling",
    "Cobenzlgasse ggü. 18 bis ggü. 22": "bezirk:Döbling",
    "Columbusgasse 23 bis 31": "bezirk:Favoriten",
    "Columbusgasse 33": "bezirk:Favoriten",
    "Columbusgasse 39 bis 47": "bezirk:Favoriten",
    "Columbusgasse 49 bis 53": "bezirk:Favoriten",
    "Columbusgasse 58-62": "bezirk:Favoriten",
    "Deutschstraße 6": "bezirk:Liesing",
    "Döblinger Hauptstraße 13 bis 23-25": "bezirk:Döbling",
    "Döblinger Hauptstraße 16 bis 28": "bezirk:Döbling",
    "Döblinger Hauptstraße 29 bis 37": "bezirk:Döbling",
    "Döblinger Hauptstraße 30 bis 42": "bezirk:Döbling",
    "Döblinger Hauptstraße 39 bis 49": "bezirk:Döbling",
    "Döblinger Hauptstraße 46 bis 52": "bezirk:Döbling",
    "Döblinger Hauptstraße 52A bis 60": "bezirk:Döbling",
    "Döblinger Hauptstraße 55 bis 63-65": "bezirk:Döbling",
    "Döblinger Hauptstraße 66 bis 74": "bezirk:Döbling",
    "Döblinger Hauptstraße 67 bis 73": "bezirk:Döbling",
    "Döblinger Hauptstraße 76 bis 80": "bezirk:Döbling",
    "Döblinger Hauptstraße 77 bis 83": "bezirk:Döbling",
    "Döblinger Hauptstraße 7B bis 11": "bezirk:Döbling",
    "Döblinger Hauptstraße 88": "bezirk:Döbling",
    "Döblinger Hauptstraße 90": "bezirk:Döbling",
    "Donaufelder Straße 1-3 bis 29": "bezirk:Floridsdorf",
    "Donaufelder Straße 2 bis 22": "bezirk:Floridsdorf",
    "Dornerplatz 3 bis 7": "bezirk:Hernals",
    "Dreiständegasse 2": "bezirk:Liesing",
    "Enkplatz 1 bis 2": "bezirk:Simmering",
    "Enkplatz 2 bis 3": "bezirk:Simmering",
    "Enkplatz 6-7, Stiege 4": "bezirk:Simmering",
    "Erbpostgasse 30": "bezirk:Floridsdorf",
    "Erdberger Lände 32 bis 36": "bezirk:Landstraße",
    "Erdberger Lände ggü. 34 bis ggü. 36": "bezirk:Landstraße",
    "Erdbergstraße 116 bis 120A": "bezirk:Landstraße",
    "Erdbergstraße 122 bis 126": "bezirk:Landstraße",
    "Erdbergstraße 47 bis 53": "bezirk:Landstraße",
    "Erdbergstraße 55 bis 57": "bezirk:Landstraße",
    "Erdbergstraße 59 bis 69": "bezirk:Landstraße",
    "Erdbergstraße 64X bis 70": "bezirk:Landstraße",
    "Erdbergstraße 72 bis 74": "bezirk:Landstraße",
    "Erdbergstraße 78-80 bis 92": "bezirk:Landstraße",
    "Erdbergstraße 81 bis 97": "bezirk:Landstraße",
    "Erlachgasse 90 bis 92": "bezirk:Favoriten",
    "Eßlinger Hauptstraße 76 bis 86": "bezirk:Donaustadt",
    "Eßlinger Hauptstraße 81 bis 87": "bezirk:Donaustadt",
    "Eßlinger Hauptstraße 89": "bezirk:Donaustadt",
    "Fasangasse 15 bis 27": "bezirk:Landstraße",
    "Fasangasse 16 bis 22": "bezirk:Landstraße",
    "Fasangasse 24 bis 28": "bezirk:Landstraße",
    "Fasangasse 31 bis 33": "bezirk:Landstraße",
    "Fasangasse 32 bis 40": "bezirk:Landstraße",
    "Fasangasse 35-37 bis 45": "bezirk:Landstraße",
    "Fasangasse 5 bis 11-13": "bezirk:Landstraße",
    "Fasangasse 6 bis 12": "bezirk:Landstraße",
    "Favoritenstraße 121": "bezirk:Favoriten",
    "Favoritenstraße 129 bis 137": "bezirk:Favoriten",
    "Favoritenstraße 134 bis 140": "bezirk:Favoriten",
    "Favoritenstraße 139 bis 141": "bezirk:Favoriten",
    "Favoritenstraße 143 bis 145": "bezirk:Favoriten",
    "Favoritenstraße 144 bis 146": "bezirk:Favoriten",
    "Favoritenstraße 147 bis 149": "bezirk:Favoriten",
    "Favoritenstraße 150 bis 158": "bezirk:Favoriten",
    "Favoritenstraße 160 bis 162": "bezirk:Favoriten",
    "Favoritenstraße 161": "bezirk:Favoriten",
    "Favoritenstraße 168 bis 170": "bezirk:Favoriten",
    "Ferrogasse 1": "bezirk:Währing",
    "Ferrogasse 2": "bezirk:Währing",
    "Floridsdorfer Hauptstraße 14 bis 16": "bezirk:Floridsdorf",
    "Floridsdorfer Hauptstraße 16 bis 20": "bezirk:Floridsdorf",
    "Floridsdorfer Hauptstraße 19 bis 27": "bezirk:Floridsdorf",
    "Floridsdorfer Hauptstraße 20": "bezirk:Floridsdorf",
    "Floridsdorfer Hauptstraße 27 bis 29": "bezirk:Floridsdorf",
    "Floridsdorfer Hauptstraße 29": "bezirk:Floridsdorf",
    "Floridsdorfer Hauptstraße 32": "bezirk:Floridsdorf",
    "Floridsdorfer Hauptstraße 33 bis 35": "bezirk:Floridsdorf",
    "Floridsdorfer Hauptstraße 34 bis 40": "bezirk:Floridsdorf",
    "Floridsdorfer Hauptstraße 37 bis 39": "bezirk:Floridsdorf",
    "Floridsdorfer Hauptstraße 39 bis 41": "bezirk:Floridsdorf",
    "Floridsdorfer Markt 1": "bezirk:Floridsdorf",
    "Floridsdorfer Markt 9 bis 14": "bezirk:Floridsdorf",
    "Franz-Jonas-Platz 3": "bezirk:Floridsdorf",
    "Fuhrygasse 2": "bezirk:Simmering",
    "Fuhrygasse ggü. 2": "bezirk:Simmering",
    "Genochplatz 11": "bezirk:Donaustadt",
    "Genochplatz 2 bis 5": "bezirk:Donaustadt",
    "Genochplatz 6 bis 8": "bezirk:Donaustadt",
    "Genochplatz ggü. 2 bis ggü. 5": "bezirk:Donaustadt",
    "Gersthofer Straße 18": "bezirk:Währing",
    "Gersthofer Straße 20 bis 30": "bezirk:Währing",
    "Gersthofer Straße 67 bis 71": "bezirk:Währing",
    "Gersthofer Straße 73 bis 75-77": "bezirk:Währing",
    "Gersthofer Straße 8 bis 12": "bezirk:Währing",
    "Geßlgasse 4A bis ggü. 11": "bezirk:Liesing",
    "Geßlgasse 8 bis 10": "bezirk:Liesing",
    "Geßlgasse ggü.1 bis ggü. 1A": "bezirk:Liesing",
    "Getreidemarkt": "bezirk:Mariahilf",
    "Groß-Enzersdorfer Straße 1 bis 5": "bezirk:Donaustadt",
    "Groß-Enzersdorfer Straße 2": "bezirk:Donaustadt",
    "Groß-Enzersdorfer Straße 7 bis 11": "bezirk:Donaustadt",
    "Groß-Enzersdorfer-Straße 4 bis 10": "bezirk:Donaustadt",
    "Großmarktstraße 1": "bezirk:Liesing",
    "Großmarktstraße 2A": "bezirk:Liesing",
    "Gudrunstraße 120 bis 126": "bezirk:Favoriten",
    "Gudrunstraße 128-130": "bezirk:Favoriten",
    "Gudrunstraße 137-139 bis 143": "bezirk:Favoriten",
    "Gudrunstraße 145-149": "bezirk:Favoriten",
    "Gudrunstraße 156 bis 160": "bezirk:Favoriten",
    "Gudrunstraße 162 bis 164": "bezirk:Favoriten",
    "Gudrunstraße 171 bis 173": "bezirk:Favoriten",
    "Gudrunstraße 175 bis 177": "bezirk:Favoriten",
    "Gymnasiumstraße 62 bis 68": "bezirk:Döbling",
    "Gymnasiumstraße 85": "bezirk:Döbling",
    "Gymnasiumstraße ggü. 2": "bezirk:Döbling",
    "Haeckelstraße 2 bis 4": "bezirk:Liesing",
    "Haeckelstraße ggü. 2 bis ggü. 4": "bezirk:Liesing",
    "Hannah-Arendt-Platz": "bezirk:Donaustadt",
    "Heiligenstädter Straße 138 bis 144": "bezirk:Döbling",
    "Heiligenstädter Straße 157 bis 163": "bezirk:Döbling",
    "Hernalser Hauptstraße 104 bis 110": "bezirk:Hernals",
    "Hernalser Hauptstraße 107 bis 115": "bezirk:Hernals",
    "Hernalser Hauptstraße 112 bis 122": "bezirk:Hernals",
    "Hernalser Hauptstraße 117 bis 119": "bezirk:Hernals",
    "Hernalser Hauptstraße 121 bis 123": "bezirk:Hernals",
    "Hernalser Hauptstraße 124 bis 128": "bezirk:Hernals",
    "Hernalser Hauptstraße 125 bis 133": "bezirk:Hernals",
    "Hernalser Hauptstraße 137 bis 139": "bezirk:Hernals",
    "Hernalser Hauptstraße 138A": "bezirk:Hernals",
    "Hernalser Hauptstraße 141 bis 147": "bezirk:Hernals",
    "Hernalser Hauptstraße 146 bis 152": "bezirk:Hernals",
    "Hernalser Hauptstraße 149 bis 155": "bezirk:Hernals",
    "Hernalser Hauptstraße 154 bis 160": "bezirk:Hernals",
    "Hernalser Hauptstraße 159 bis 163": "bezirk:Hernals",
    "Hernalser Hauptstraße 16 bis 18": "bezirk:Hernals",
    "Hernalser Hauptstraße 162 bis 168": "bezirk:Hernals",
    "Hernalser Hauptstraße 165 bis 169": "bezirk:Hernals",
    "Hernalser Hauptstraße 170 bis 172": "bezirk:Hernals",
    "Hernalser Hauptstraße 171 bis 173": "bezirk:Hernals",
    "Hernalser Hauptstraße 180 bis 190-192": "bezirk:Hernals",
    "Hernalser Hauptstraße 187 bis 191": "bezirk:Hernals",
    "Hernalser Hauptstraße 191a bis 195": "bezirk:Hernals",
    "Hernalser Hauptstraße 194 bis 212": "bezirk:Hernals",
    "Hernalser Hauptstraße 197 bis 205": "bezirk:Hernals",
    "Hernalser Hauptstraße 20 bis 24-26": "bezirk:Hernals",
    "Hernalser Hauptstraße 207 bis 215": "bezirk:Hernals",
    "Hernalser Hauptstraße 21 bis 33": "bezirk:Hernals",
    "Hernalser Hauptstraße 214-216 bis 220-222": "bezirk:Hernals",
    "Hernalser Hauptstraße 217 bis 219": "bezirk:Hernals",
    "Hernalser Hauptstraße 224": "bezirk:Hernals",
    "Hernalser Hauptstraße 230": "bezirk:Hernals",
    "Hernalser Hauptstraße 28 bis 38": "bezirk:Hernals",
    "Hernalser Hauptstraße 35 bis 49": "bezirk:Hernals",
    "Hernalser Hauptstraße 40 bis 54": "bezirk:Hernals",
    "Hernalser Hauptstraße 51 bis 1": "bezirk:Hernals",
    "Hernalser Hauptstraße 56 bis 72-74": "bezirk:Hernals",
    "Hernalser Hauptstraße 78 bis 94": "bezirk:Hernals",
    "Hernalser Hauptstraße 85 bis 89": "bezirk:Hernals",
    "Hernalser Hauptstraße 9 bis 19": "bezirk:Hernals",
    "Hernalser Hauptstraße 91 bis 93": "bezirk:Hernals",
    "Hernalser Hauptstraße 96": "bezirk:Hernals",
    "Hernalser Hauptstraße 99 bis 105": "bezirk:Hernals",
    "Hetzendorfer Straße 75 bis ggü. 90": "bezirk:Meidling",
    "Hetzendorfer Straße 76 bis 78": "bezirk:Meidling",
    "Hietzinger Hauptstraße 143 bis 145": "bezirk:Hietzing",
    "Hietzinger Hauptstraße 149-151": "bezirk:Hietzing",
    "Hietzinger Hauptstraße 166 bis 168": "bezirk:Hietzing",
    "Hietzinger Hauptstraße 170 bis 174": "bezirk:Hietzing",
    "Hietzinger Hauptstraße 3 bis 19": "bezirk:Hietzing",
    "Hietzinger Hauptstraße 32": "bezirk:Hietzing",
    "Hietzinger Hauptstraße 4 bis 8": "bezirk:Hietzing",
    "Hietzinger Hauptstraße 67 bis 73": "bezirk:Hietzing",
    "Hietzinger Hauptstraße 72 bis 82-84": "bezirk:Hietzing",
    "Himmelstraße 9 bis 15": "bezirk:Döbling",
    "Hormayrgasse 1 bis 7a": "bezirk:Hernals",
    "Hormayrgasse 2 bis 4": "bezirk:Hernals",
    "Hormayrgasse 6": "bezirk:Hernals",
    "Hormayrgasse 7a": "bezirk:Hernals",
    "Hütteldorfer Straße 102 bis 104": "bezirk:Penzing",
    "Hütteldorfer Straße 105 bis 109": "bezirk:Rudolfsheim-Fünfhaus",
    "Hütteldorfer Straße 110 bis 114": "bezirk:Penzing",
    "Hütteldorfer Straße 111 bis 111a": "bezirk:Penzing",
    "Hütteldorfer Straße 113 bis 115": "bezirk:Penzing",
    "Hütteldorfer Straße 116 bis 122": "bezirk:Penzing",
    "Hütteldorfer Straße 123": "bezirk:Penzing",
    "Hütteldorfer Straße 125 bis 127": "bezirk:Penzing",
    "Hütteldorfer Straße 126": "bezirk:Penzing",
    "Hütteldorfer Straße 128": "bezirk:Penzing",
    "Hütteldorfer Straße 129 bis 133": "bezirk:Penzing",
    "Hütteldorfer Straße 130 bis 130d": "bezirk:Penzing",
    "Hütteldorfer Straße 135 bis 139": "bezirk:Penzing",
    "Hütteldorfer Straße 141 bis 145": "bezirk:Penzing",
    "Hütteldorfer Straße 142 bis 146": "bezirk:Penzing",
    "Hütteldorfer Straße 148 bis 156-158": "bezirk:Penzing",
    "Hütteldorfer Straße 155 bis 163-165": "bezirk:Penzing",
    "Hütteldorfer Straße 171 bis 181": "bezirk:Penzing",
    "Hütteldorfer Straße 183 bis 197": "bezirk:Penzing",
    "Hütteldorfer Straße 213 bis 215": "bezirk:Penzing",
    "Hütteldorfer Straße 217 bis 225": "bezirk:Penzing",
    "Hütteldorfer Straße 28 bis 32": "bezirk:Rudolfsheim-Fünfhaus",
    "Hütteldorfer Straße 34 bis 38": "bezirk:Rudolfsheim-Fünfhaus",
    "Hütteldorfer Straße 40 bis 44-46": "bezirk:Rudolfsheim-Fünfhaus",
    "Hütteldorfer Straße 44-46 bis 48": "bezirk:Rudolfsheim-Fünfhaus",
    "Hütteldorfer Straße 50 bis 56": "bezirk:Rudolfsheim-Fünfhaus",
    "Hütteldorfer Straße 58 bis 60": "bezirk:Rudolfsheim-Fünfhaus",
    "Hütteldorfer Straße 59 bis 61": "bezirk:Rudolfsheim-Fünfhaus",
    "Hütteldorfer Straße 62 bis 64": "bezirk:Rudolfsheim-Fünfhaus",
    "Hütteldorfer Straße 63 bis 67": "bezirk:Rudolfsheim-Fünfhaus",
    "Hütteldorfer Straße 66 bis 70": "bezirk:Rudolfsheim-Fünfhaus",
    "Hütteldorfer Straße 69 bis 71": "bezirk:Rudolfsheim-Fünfhaus",
    "Hütteldorfer Straße 77 bis 81": "bezirk:Rudolfsheim-Fünfhaus",
    "Hütteldorfer Straße 78 bis 82": "bezirk:Penzing",
    "Hütteldorfer Straße 81a": "bezirk:Rudolfsheim-Fünfhaus",
    "Hütteldorfer Straße 81b": "bezirk:Rudolfsheim-Fünfhaus",
    "Hütteldorfer Straße 83 bis 87": "bezirk:Rudolfsheim-Fünfhaus",
    "Hütteldorfer Straße 84-86 bis 88": "bezirk:Penzing",
    "Hütteldorfer Straße 90 bis 100": "bezirk:Penzing",
    "Hütteldorfer Straße 91 bis 95": "bezirk:Rudolfsheim-Fünfhaus",
    "Hütteldorfer Straße 97 bis 103": "bezirk:Rudolfsheim-Fünfhaus",
    "Hütteldorfer Straße ggü. 167 bis ggü. 177": "bezirk:Penzing",
    "Johann-Nepomuk-Vogl-Platz 8A bis 9A": "bezirk:Währing",
    "Johann-Nepomuk-Vogl-Platz ggü. 8A bis ggü. 9A": "bezirk:Währing",
    "Jörgerstraße 1 bis 7": "bezirk:Hernals",
    "Jörgerstraße 10 bis 16": "bezirk:Währing",
    "Jörgerstraße 18": "bezirk:Währing",
    "Jörgerstraße 20 bis 26": "bezirk:Hernals",
    "Jörgerstraße 28 bis 30": "bezirk:Hernals",
    "Jörgerstraße 32 bis 38": "bezirk:Hernals",
    "Jörgerstraße 4-6": "bezirk:Währing",
    "Jörgerstraße 42-44 bis 46-48": "bezirk:Hernals",
    "Jörgerstraße 50 bis 56-58": "bezirk:Hernals",
    "Jörgerstraße 9 bis 13": "bezirk:Hernals",
    "Josefstädter Straße 30": "bezirk:Josefstadt",
    "Josefstädter Straße 33": "bezirk:Josefstadt",
    "Josefstädter Straße 38 bis 40": "bezirk:Josefstadt",
    "Josefstädter Straße 42": "bezirk:Josefstadt",
    "Josefstädter Straße 43-45 bis 61": "bezirk:Josefstadt",
    "Josefstädter Straße 46 bis 48": "bezirk:Josefstadt",
    "Josefstädter Straße 50 bis 54": "bezirk:Josefstadt",
    "Josefstädter Straße 56 bis 60": "bezirk:Josefstadt",
    "Josefstädter Straße 63 bis 67": "bezirk:Josefstadt",
    "Josefstädter Straße 66 bis 74": "bezirk:Josefstadt",
    "Josefstädter Straße 69 bis 73": "bezirk:Josefstadt",
    "Josefstädter Straße 76 bis 80": "bezirk:Josefstadt",
    "Josefstädter Straße 85 bis 89": "bezirk:Josefstadt",
    "Josefstädter Straße 9 bis 13": "bezirk:Josefstadt",
    "Josefstädter Straße 93-97 bis 101": "bezirk:Josefstadt",
    "Kagraner Platz 46 bis 52": "bezirk:Donaustadt",
    "Kagraner Platz 6 bis 8": "bezirk:Donaustadt",
    "Kaisermühlenstraße": "bezirk:Donaustadt",
    "Kalksburg-Kirchenplatz 1": "bezirk:Liesing",
    "Kalksburg-Kirchenplatz ggü. 1": "bezirk:Liesing",
    "Kalvarienberggasse 21 bis 23": "bezirk:Hernals",
    "Kalvarienberggasse 25 bis 27": "bezirk:Hernals",
    "Kalvarienberggasse 28 bis 28a": "bezirk:Hernals",
    "Kalvarienberggasse 30 bis 36": "bezirk:Hernals",
    "Kalvarienberggasse 33": "bezirk:Hernals",
    "Kalvarienberggasse 35 bis 39": "bezirk:Hernals",
    "Kalvarienberggasse 38 bis 42": "bezirk:Hernals",
    "Kalvarienberggasse 41 bis 45": "bezirk:Hernals",
    "Kalvarienberggasse 44 bis 48": "bezirk:Hernals",
    "Kalvarienberggasse 47 bis 51": "bezirk:Hernals",
    "Kalvarienberggasse 50 bis 54": "bezirk:Hernals",
    "Kalvarienberggasse 53 bis 61": "bezirk:Hernals",
    "Kalvarienberggasse 56 bis 64": "bezirk:Hernals",
    "Kalvarienberggasse 63 bis 71": "bezirk:Hernals",
    "Kalvarienberggasse 66 bis 74": "bezirk:Hernals",
    "Kardinal-Nagl-Platz 12 bis 16": "bezirk:Landstraße",
    "Kardinal-Nagl-Platz ggü. 12 bis ggü. 14": "bezirk:Landstraße",
    "Keplerplatz 1": "bezirk:Favoriten",
    "Keplerplatz 3 bis 4": "bezirk:Favoriten",
    "Keplerplatz 8 bis 9": "bezirk:Favoriten",
    "Keplerplatz ggü. 1": "bezirk:Favoriten",
    "Keplerplatz ggü. 8 bis ggü. 9": "bezirk:Favoriten",
    "Keplerplatz ggü.2 bis ggü. 4": "bezirk:Favoriten",
    "Kettenbrücke": "bezirk:Mariahilf",
    "Klosterneuburger Straße 20 bis 28": "bezirk:Brigittenau",
    "Klosterneuburger Straße 29 bis 41": "bezirk:Brigittenau",
    "Klosterneuburger Straße 30 bis 40": "bezirk:Brigittenau",
    "Klosterneuburger Straße 42 bis 48": "bezirk:Brigittenau",
    "Klosterneuburger Straße 43 bis 57": "bezirk:Brigittenau",
    "Kreuzgasse 36 bis 44": "bezirk:Währing",
    "Lainzer Straße 11 bis 21": "bezirk:Hietzing",
    "Lainzer Straße 123A bis 131": "bezirk:Hietzing",
    "Lainzer Straße 126 bis 130": "bezirk:Hietzing",
    "Lainzer Straße 132A bis 132C": "bezirk:Hietzing",
    "Lainzer Straße 135": "bezirk:Hietzing",
    "Lainzer Straße 3-5 bis 7": "bezirk:Hietzing",
    "Lainzer Straße 4 bis 14": "bezirk:Hietzing",
    "Landstraßer Hauptstraße 1": "bezirk:Landstraße",
    "Landstraßer Hauptstraße 103": "bezirk:Landstraße",
    "Landstraßer Hauptstraße 105 bis 113": "bezirk:Landstraße",
    "Landstraßer Hauptstraße 110 bis 116": "bezirk:Landstraße",
    "Landstraßer Hauptstraße 12 bis 22": "bezirk:Landstraße",
    "Landstraßer Hauptstraße 19 bis 23": "bezirk:Landstraße",
    "Landstraßer Hauptstraße 2": "bezirk:Landstraße",
    "Landstraßer Hauptstraße 29 bis 35": "bezirk:Landstraße",
    "Landstraßer Hauptstraße 32 bis 40": "bezirk:Landstraße",
    "Landstraßer Hauptstraße 4": "bezirk:Landstraße",
    "Landstraßer Hauptstraße 4 bis 4A": "bezirk:Landstraße",
    "Landstraßer Hauptstraße 44 bis 50": "bezirk:Landstraße",
    "Landstraßer Hauptstraße 4A bis 6": "bezirk:Landstraße",
    "Landstraßer Hauptstraße 55 bis 59": "bezirk:Landstraße",
    "Landstraßer Hauptstraße 56 bis 60": "bezirk:Landstraße",
    "Landstraßer Hauptstraße 65 bis 67": "bezirk:Landstraße",
    "Landstraßer Hauptstraße 68 bis 78-80": "bezirk:Landstraße",
    "Landstraßer Hauptstraße 7 bis 9": "bezirk:Landstraße",
    "Landstraßer Hauptstraße 71 bis 85": "bezirk:Landstraße",
    "Landstraßer Hauptstraße 86 bis 88": "bezirk:Landstraße",
    "Landstraßer Hauptstraße 92-94 bis 106": "bezirk:Landstraße",
    "Laxenburger Straße 18": "bezirk:Favoriten",
    "Laxenburger Straße 20 bis 22": "bezirk:Favoriten",
    "Laxenburger Straße 28 bis 36": "bezirk:Favoriten",
    "Laxenburger Straße 37 bis 41": "bezirk:Favoriten",
    "Laxenburger Straße 38 bis 42": "bezirk:Favoriten",
    "Laxenburger Straße 44 bis 46": "bezirk:Favoriten",
    "Laxenburger Straße 49-57": "bezirk:Favoriten",
    "Laxenburger Straße 59 bis 63": "bezirk:Favoriten",
    "Laxenburger Straße 65 / Quellenplatz 3 2 bis 65": "bezirk:Favoriten",
    "Leibnizgasse 11 bis 15": "bezirk:Favoriten",
    "Lerchenfelder Straße 1-3 bis 5": "bezirk:Neubau",
    "Lerchenfelder Straße 112 bis 132": "bezirk:Josefstadt",
    "Lerchenfelder Straße 113 bis 117": "bezirk:Neubau",
    "Lerchenfelder Straße 12 bis 16": "bezirk:Josefstadt",
    "Lerchenfelder Straße 121 bis 147": "bezirk:Neubau",
    "Lerchenfelder Straße 134 bis 158": "bezirk:Josefstadt",
    "Lerchenfelder Straße 15 bis 27": "bezirk:Neubau",
    "Lerchenfelder Straße 18-24": "bezirk:Josefstadt",
    "Lerchenfelder Straße 2": "bezirk:Josefstadt",
    "Lerchenfelder Straße 26 bis 36": "bezirk:Josefstadt",
    "Lerchenfelder Straße 33 bis 39": "bezirk:Neubau",
    "Lerchenfelder Straße 4": "bezirk:Josefstadt",
    "Lerchenfelder Straße 42 bis 78-80": "bezirk:Josefstadt",
    "Lerchenfelder Straße 53 bis 57": "bezirk:Neubau",
    "Lerchenfelder Straße 59": "bezirk:Neubau",
    "Lerchenfelder Straße 63 bis 67": "bezirk:Neubau",
    "Lerchenfelder Straße 7 bis 11": "bezirk:Neubau",
    "Lerchenfelder Straße 8 bis 10": "bezirk:Josefstadt",
    "Lerchenfelder Straße 81 bis 99": "bezirk:Neubau",
    "Lerchenfelder Straße 86 bis 88-90": "bezirk:Josefstadt",
    "Lerchenfelder Straße 92 bis 94-98": "bezirk:Josefstadt",
    "Levasseurgasse 1": "bezirk:Liesing",
    "Levasseurgasse 15 bis 19": "bezirk:Liesing",
    "Levasseurgasse 2 bis 4": "bezirk:Liesing",
    "Levasseurgasse 5 bis 7": "bezirk:Liesing",
    "Linke Wienzeile ggü. 20 bis ggü. 38": "bezirk:Mariahilf",
    "Linzer Straße 20 bis 28": "bezirk:Penzing",
    "Linzer Straße 214 bis 226": "bezirk:Penzing",
    "Linzer Straße 228": "bezirk:Penzing",
    "Linzer Straße 236 bis 254": "bezirk:Penzing",
    "Linzer Straße 241 bis 257": "bezirk:Penzing",
    "Linzer Straße 256 bis 264": "bezirk:Penzing",
    "Linzer Straße 261 bis 265": "bezirk:Penzing",
    "Linzer Straße 269": "bezirk:Penzing",
    "Linzer Straße 271 bis 283": "bezirk:Penzing",
    "Linzer Straße 313 bis 315": "bezirk:Penzing",
    "Linzer Straße 365 bis 369": "bezirk:Penzing",
    "Linzer Straße 371": "bezirk:Penzing",
    "Linzer Straße 375 bis 379": "bezirk:Penzing",
    "Linzer Straße 383": "bezirk:Penzing",
    "Linzer Straße 395 bis 397": "bezirk:Penzing",
    "Linzer Straße 396 bis 398": "bezirk:Penzing",
    "Linzer Straße 403 bis 409": "bezirk:Penzing",
    "Linzer Straße 412 bis 414a": "bezirk:Penzing",
    "Linzer Straße 42": "bezirk:Penzing",
    "Linzer Straße 44 bis 46": "bezirk:Penzing",
    "Linzer Straße 48 bis 54": "bezirk:Penzing",
    "Linzer Straße 53 bis 65": "bezirk:Penzing",
    "Linzer Straße 67": "bezirk:Penzing",
    "Linzer Straße 77 bis 85": "bezirk:Penzing",
    "Maria-Tusch-Gasse 12": "bezirk:Donaustadt",
    "Maria-Tusch-Gasse 13": "bezirk:Donaustadt",
    "Maria-Tusch-Straße 14": "bezirk:Donaustadt",
    "Maria-Tusch-Straße 18": "bezirk:Donaustadt",
    "Maria-Tusch-Straße 19": "bezirk:Donaustadt",
    "Maria-Tusch-Straße 2 bis 4": "bezirk:Donaustadt",
    "Maria-Tusch-Straße 23 bis 25": "bezirk:Donaustadt",
    "Maria-Tusch-Straße 24 bis 30": "bezirk:Donaustadt",
    "Maria-Tusch-Straße 33": "bezirk:Donaustadt",
    "Maria-Tusch-Straße 6": "bezirk:Donaustadt",
    "Maria-Tusch-Straße 8": "bezirk:Donaustadt",
    "Maria-Tusch-Straße ggü.23 bis 22": "bezirk:Donaustadt",
    "Mariahilfer Straße 122 bis 124": "bezirk:Neubau",
    "Mariahilfer Straße 128": "bezirk:Neubau",
    "Mariahilfer Straße 133": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 134 bis 136": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 135 bis 143": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 138 bis 140": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 142 bis 144": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 145 bis 149": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 146 bis 148": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 149": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 150 bis 152": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 151 bis 153": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 153 bis 163": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 154 bis 160": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 162 bis 164": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 165 bis 167": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 169": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 172": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 173-175 bis 179": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 178 bis 182": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 184": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 191 bis 193": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 195 bis 209": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 196 bis 198": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 198 bis 204": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 206": "bezirk:Rudolfsheim-Fünfhaus",
    "Mariahilfer Straße 217A bis ggü. 198": "bezirk:Rudolfsheim-Fünfhaus",
    "Martinstraße 93 bis 97": "bezirk:Währing",
    "Marxergasse 1A": "bezirk:Landstraße",
    "Märzstraße 40 bis 44": "bezirk:Rudolfsheim-Fünfhaus",
    "Märzstraße 49 bis 55": "bezirk:Rudolfsheim-Fünfhaus",
    "Märzstraße 52 bis 56": "bezirk:Rudolfsheim-Fünfhaus",
    "Märzstraße 57 bis 61": "bezirk:Rudolfsheim-Fünfhaus",
    "Märzstraße 58 bis 62": "bezirk:Rudolfsheim-Fünfhaus",
    "Märzstraße 64": "bezirk:Rudolfsheim-Fünfhaus",
    "Matzleinsdorfer Platz 3 bis 5": "bezirk:Margareten",
    "Maurer Hauptplatz 11": "bezirk:Liesing",
    "Maurer Hauptplatz 6 bis 10": "bezirk:Liesing",
    "Maurer Hauptplatz 9 bis 11": "bezirk:Liesing",
    "Maurer Hauptplatz ggü. 11": "bezirk:Liesing",
    "Meidlinger Hauptstraße 3 bis 7-9": "bezirk:Meidling",
    "Meidlinger Hauptstraße 57-59 bis 73": "bezirk:Meidling",
    "Meidlinger Hauptstraße 7-9 bis 13": "bezirk:Meidling",
    "Meidlinger Hauptstraße 75 bis 77-79": "bezirk:Meidling",
    "Mühlsangergasse 42": "bezirk:Simmering",
    "Neubaugasse 52 bis 70": "bezirk:Neubau",
    "Neubaugasse 79": "bezirk:Neubau",
    "Neubaugasse 80": "bezirk:Neubau",
    "Neubaugasse 82 bis 88": "bezirk:Neubau",
    "Neulerchenfelder Straße 17 bis 21": "bezirk:Ottakring",
    "Neulerchenfelder Straße 24 bis 30": "bezirk:Ottakring",
    "Neulerchenfelder Straße 3 bis 5-7": "bezirk:Ottakring",
    "Neulerchenfelder Straße 31 bis 35": "bezirk:Ottakring",
    "Neulerchenfelder Straße 34 bis 42": "bezirk:Ottakring",
    "Neulerchenfelder Straße 39 bis 45": "bezirk:Ottakring",
    "Neulerchenfelder Straße 4 bis 10": "bezirk:Ottakring",
    "Neulerchenfelder Straße 48 bis 60": "bezirk:Ottakring",
    "Neulerchenfelder Straße 70 bis 76": "bezirk:Ottakring",
    "Neulerchenfelder Straße 78 bis 82": "bezirk:Ottakring",
    "Neulerchenfelder Straße 81 bis 87": "bezirk:Ottakring",
    "Neulerchenfelder Straße 9": "bezirk:Ottakring",
    "Neulerchenfelder Straße ggü. 79 bis ggü. 81": "bezirk:Ottakring",
    "Niederhofstraße 1 bis 5": "bezirk:Meidling",
    "Niederhofstraße 10-12": "bezirk:Meidling",
    "Niederhofstraße 13 bis 15": "bezirk:Meidling",
    "Niederhofstraße 17 bis 19": "bezirk:Meidling",
    "Niederhofstraße 18 bis 24": "bezirk:Meidling",
    "Niederhofstraße 2 bis 6": "bezirk:Meidling",
    "Niederhofstraße 21-23": "bezirk:Meidling",
    "Niederhofstraße 37 bis 39": "bezirk:Meidling",
    "Niederhofstraße 7 bis 11": "bezirk:Meidling",
    "Niederhofstraße 8": "bezirk:Meidling",
    "Niederhofstraße ggü. 17": "bezirk:Meidling",
    "Nisselgasse 5 bis 7": "bezirk:Penzing",
    "Nußdorfer Platz 1-2A": "bezirk:Döbling",
    "Nußdorfer Platz 5 bis 8": "bezirk:Döbling",
    "Nußdorfer Platz ggü. 5 bis ggü. 8": "bezirk:Döbling",
    "Obkirchergasse 19 bis 27": "bezirk:Döbling",
    "Obkirchergasse 22 bis 30A": "bezirk:Döbling",
    "Obkirchergasse 29 bis 45": "bezirk:Döbling",
    "Obkirchergasse 32 bis 38": "bezirk:Döbling",
    "Ottakringer Straße 106": "bezirk:Ottakring",
    "Ottakringer Straße 108 bis 122": "bezirk:Ottakring",
    "Ottakringer Straße 109 bis 115": "bezirk:Ottakring",
    "Ottakringer Straße 117 bis 119": "bezirk:Ottakring",
    "Ottakringer Straße 124 bis 136": "bezirk:Ottakring",
    "Ottakringer Straße 131 bis 139": "bezirk:Ottakring",
    "Ottakringer Straße 138 bis 142": "bezirk:Ottakring",
    "Ottakringer Straße 141 bis 145": "bezirk:Ottakring",
    "Ottakringer Straße 147 bis 153": "bezirk:Ottakring",
    "Ottakringer Straße 152 bis 158": "bezirk:Ottakring",
    "Ottakringer Straße 160 bis 166": "bezirk:Ottakring",
    "Ottakringer Straße 161 bis 165": "bezirk:Ottakring",
    "Ottakringer Straße 167 bis 179": "bezirk:Ottakring",
    "Ottakringer Straße 168 bis 170": "bezirk:Ottakring",
    "Ottakringer Straße 17 bis 23": "bezirk:Ottakring",
    "Ottakringer Straße 176 bis 180": "bezirk:Ottakring",
    "Ottakringer Straße 18 bis 22": "bezirk:Hernals",
    "Ottakringer Straße 181-187 bis 193": "bezirk:Ottakring",
    "Ottakringer Straße 184 bis 188": "bezirk:Ottakring",
    "Ottakringer Straße 190-192": "bezirk:Ottakring",
    "Ottakringer Straße 24 bis 30": "bezirk:Hernals",
    "Ottakringer Straße 25 bis 31": "bezirk:Ottakring",
    "Ottakringer Straße 37": "bezirk:Ottakring",
    "Ottakringer Straße 39 bis 43": "bezirk:Ottakring",
    "Ottakringer Straße 42 bis 48": "bezirk:Hernals",
    "Ottakringer Straße 45 bis 49": "bezirk:Ottakring",
    "Ottakringer Straße 50 bis 54": "bezirk:Hernals",
    "Ottakringer Straße 57": "bezirk:Ottakring",
    "Ottakringer Straße 58 bis 60": "bezirk:Hernals",
    "Ottakringer Straße 68 bis 72": "bezirk:Hernals",
    "Ottakringer Straße 73 bis 75": "bezirk:Ottakring",
    "Ottakringer Straße 76 bis 78": "bezirk:Hernals",
    "Ottakringer Straße 84 bis 86": "bezirk:Hernals",
    "Ottakringer Straße 87 bis 97": "bezirk:Ottakring",
    "Ottakringer Straße 9 bis 13": "bezirk:Hernals",
    "Ottakringer Straße 90 bis 96": "bezirk:Hernals",
    "Ottakringer Straße 99 bis 107": "bezirk:Ottakring",
    "Perfektastraße 100": "bezirk:Liesing",
    "Pernerstorfergasse 29 bis 31": "bezirk:Favoriten",
    "Pohlgasse 10 bis 18": "bezirk:Meidling",
    "Pohlgasse 11 bis 15": "bezirk:Meidling",
    "Pohlgasse 2-4 bis 8": "bezirk:Meidling",
    "Pohlgasse 3": "bezirk:Meidling",
    "Pohlgasse 5 bis 9": "bezirk:Meidling",
    "Pouthongasse 13 bis 15": "bezirk:Rudolfsheim-Fünfhaus",
    "Pouthongasse 14 bis 16": "bezirk:Rudolfsheim-Fünfhaus",
    "Prager Straße 11 bis 13": "bezirk:Floridsdorf",
    "Prager Straße 2 bis 14": "bezirk:Floridsdorf",
    "Prager Straße 42 bis 68": "bezirk:Floridsdorf",
    "Prager Straße 5 bis 7": "bezirk:Floridsdorf",
    "Prager Straße 61 bis 81": "bezirk:Floridsdorf",
    "Prager Straße 80-86": "bezirk:Floridsdorf",
    "Prager Straße 93-99": "bezirk:Floridsdorf",
    "Praterstraße 21 bis 23": "bezirk:Leopoldstadt",
    "Praterstraße 24 bis 28": "bezirk:Leopoldstadt",
    "Praterstraße 25 bis 29": "bezirk:Leopoldstadt",
    "Praterstraße 33 bis 37": "bezirk:Leopoldstadt",
    "Praterstraße 41 bis 45": "bezirk:Leopoldstadt",
    "Praterstraße 44-46 bis 50": "bezirk:Leopoldstadt",
    "Praterstraße 51 bis 57": "bezirk:Leopoldstadt",
    "Praterstraße 54 bis 68": "bezirk:Leopoldstadt",
    "Praterstraße 57 bis 63": "bezirk:Leopoldstadt",
    "Praterstraße 70 bis 78": "bezirk:Leopoldstadt",
    "Quellenstraße 123 bis 125": "bezirk:Favoriten",
    "Quellenstraße 127 bis 129": "bezirk:Favoriten",
    "Quellenstraße 131 bis 135": "bezirk:Favoriten",
    "Quellenstraße 141 bis 147": "bezirk:Favoriten",
    "Quellenstraße 72 bis 74": "bezirk:Favoriten",
    "Quellenstraße 76 bis 78": "bezirk:Favoriten",
    "Quellenstraße 88 / Quellenplatz 8 8 bis 88": "bezirk:Favoriten",
    "Quellenstraße 90 bis 96": "bezirk:Favoriten",
    "Raaber-Bahn-Gasse 19 bis 21": "bezirk:Favoriten",
    "Raaber-Bahn-Gasse 20-22": "bezirk:Favoriten",
    "Rauchgasse 37 bis 43": "bezirk:Meidling",
    "Rauchgasse 38 bis 46": "bezirk:Meidling",
    "Rechte Wienzeile ggü. 1 bis ggü. 7": "bezirk:Wieden",
    "Rechte Wienzeile ggü. 19 bis ggü. 39": "bezirk:Wieden",
    "Rechte Wienzeile ggü. 9 bis ggü. 13": "bezirk:Wieden",
    "Reinprechtsdorfer Straße 11 bis 13": "bezirk:Margareten",
    "Reinprechtsdorfer Straße 15 bis 17": "bezirk:Margareten",
    "Reinprechtsdorfer Straße 16 bis 18": "bezirk:Margareten",
    "Reinprechtsdorfer Straße 19 bis 27": "bezirk:Margareten",
    "Reinprechtsdorfer Straße 1B bis 1C": "bezirk:Margareten",
    "Reinprechtsdorfer Straße 1C": "bezirk:Margareten",
    "Reinprechtsdorfer Straße 2 bis 6": "bezirk:Margareten",
    "Reinprechtsdorfer Straße 20 bis 22": "bezirk:Margareten",
    "Reinprechtsdorfer Straße 24-26": "bezirk:Margareten",
    "Reinprechtsdorfer Straße 28 bis 30": "bezirk:Margareten",
    "Reinprechtsdorfer Straße 29 bis 35-37": "bezirk:Margareten",
    "Reinprechtsdorfer Straße 3 bis 5": "bezirk:Margareten",
    "Reinprechtsdorfer Straße 32 bis 40": "bezirk:Margareten",
    "Reinprechtsdorfer Straße 39 bis 45": "bezirk:Margareten",
    "Reinprechtsdorfer Straße 44 bis 46": "bezirk:Margareten",
    "Reinprechtsdorfer Straße 47 bis 51": "bezirk:Margareten",
    "Reinprechtsdorfer Straße 50 bis 52": "bezirk:Margareten",
    "Reinprechtsdorfer Straße 54 bis 58-60": "bezirk:Margareten",
    "Reinprechtsdorfer Straße 55 bis 59-61": "bezirk:Margareten",
    "Reinprechtsdorfer Straße 62 bis 70": "bezirk:Margareten",
    "Reinprechtsdorfer Straße 7 bis 9": "bezirk:Margareten",
    "Reinprechtsdorfer Straße 8 bis 14": "bezirk:Margareten",
    "Reschgasse 20 bis 24": "bezirk:Meidling",
    "Reschgasse 21 bis 29": "bezirk:Meidling",
    "Reschgasse 6 bis 18": "bezirk:Meidling",
    "Richard-Strauss-Straße 6": "bezirk:Liesing",
    "Richard-Wagner-Platz 17 bis 18": "bezirk:Ottakring",
    "Richard-Wagner-Platz ggü. 17": "bezirk:Ottakring",
    "Salierigasse 39 bis 41": "bezirk:Währing",
    "Salierigasse 42": "bezirk:Währing",
    "Schloßhofer Straße 22 bis 30": "bezirk:Floridsdorf",
    "Schloßhofer Straße 25 bis 31": "bezirk:Floridsdorf",
    "Schöpfleuthnergasse 25": "bezirk:Floridsdorf",
    "Schüttaustraße 1-39; Stiege 1 bis 1-39; Stiege 7": "bezirk:Donaustadt",
    "Schüttaustraße 4-10 bis 14": "bezirk:Donaustadt",
    "Sechshauser Straße 13 bis 25": "bezirk:Rudolfsheim-Fünfhaus",
    "Sechshauser Straße 20 bis 30": "bezirk:Rudolfsheim-Fünfhaus",
    "Sechshauser Straße 33 bis 39": "bezirk:Rudolfsheim-Fünfhaus",
    "Sechshauser Straße 41 bis 43": "bezirk:Rudolfsheim-Fünfhaus",
    "Sechshauser Straße 45 bis 53": "bezirk:Rudolfsheim-Fünfhaus",
    "Sechshauser Straße 48 bis 50": "bezirk:Rudolfsheim-Fünfhaus",
    "Sechshauser Straße 5 bis 9": "bezirk:Rudolfsheim-Fünfhaus",
    "Sechshauser Straße 6 bis 16": "bezirk:Rudolfsheim-Fünfhaus",
    "Senefeldergasse 12 bis 20": "bezirk:Favoriten",
    "Senefeldergasse 2 bis 10": "bezirk:Favoriten",
    "Siegesplatz 10 bis 11": "bezirk:Donaustadt",
    "Siegesplatz 14": "bezirk:Donaustadt",
    "Siegesplatz 21 bis 26": "bezirk:Donaustadt",
    "Siegesplatz 7 bis 9": "bezirk:Donaustadt",
    "Sieveringer Straße 4": "bezirk:Döbling",
    "Sieveringer Straße 7 bis 15": "bezirk:Döbling",
    "Simmeringer Hauptstraße 100 bis 100A": "bezirk:Simmering",
    "Simmeringer Hauptstraße 102-104 bis 108A": "bezirk:Simmering",
    "Simmeringer Hauptstraße 107": "bezirk:Simmering",
    "Simmeringer Hauptstraße 108B bis 110": "bezirk:Simmering",
    "Simmeringer Hauptstraße 115 bis 119": "bezirk:Simmering",
    "Simmeringer Hauptstraße 116-118 bis 120": "bezirk:Simmering",
    "Simmeringer Hauptstraße 128 bis 130": "bezirk:Simmering",
    "Simmeringer Hauptstraße 131 bis 137": "bezirk:Simmering",
    "Simmeringer Hauptstraße 141 bis 143": "bezirk:Simmering",
    "Simmeringer Hauptstraße 145 bis 147": "bezirk:Simmering",
    "Simmeringer Hauptstraße 151 bis 151A": "bezirk:Simmering",
    "Simmeringer Hauptstraße 46 bis 48": "bezirk:Simmering",
    "Simmeringer Hauptstraße 47-49": "bezirk:Simmering",
    "Simmeringer Hauptstraße 50 bis 58": "bezirk:Simmering",
    "Simmeringer Hauptstraße 55 bis 59-61": "bezirk:Simmering",
    "Simmeringer Hauptstraße 60-64 bis 68-74": "bezirk:Simmering",
    "Simmeringer Hauptstraße 76 bis 80-82": "bezirk:Simmering",
    "Simmeringer Hauptstraße 81 bis 87A": "bezirk:Simmering",
    "Simmeringer Hauptstraße 86 bis 90-92": "bezirk:Simmering",
    "Simmeringer Hauptstraße 91 bis 95": "bezirk:Simmering",
    "Simmeringer Hauptstraße 97 bis 99": "bezirk:Simmering",
    "Simonygasse 2 bis 12": "bezirk:Währing",
    "Sonnbergplatz 1 bis 4": "bezirk:Döbling",
    "Sonnbergplatz 5 bis 7": "bezirk:Döbling",
    "Sonnbergplatz ggü. 1 bis ggü. 2": "bezirk:Döbling",
    "Sonnbergplatz ggü. 4 bis ggü. 5": "bezirk:Döbling",
    "Sonnbergplatz ggü. 8": "bezirk:Döbling",
    "Sonnbergplatz ggü.6 bis ggü. 7": "bezirk:Döbling",
    "Speisinger Straße 260-262": "bezirk:Liesing",
    "Speisinger Straße 41 bis 47-53": "bezirk:Hietzing",
    "Speisinger Straße 46 bis 50": "bezirk:Hietzing",
    "Speisinger Straße ggü. 260-262": "bezirk:Liesing",
    "Stadlauer Straße 18 bis 26": "bezirk:Donaustadt",
    "Stadlauer Straße 26": "bezirk:Donaustadt",
    "Stadlauer Straße 28 bis 30-32": "bezirk:Donaustadt",
    "Stadlauer Straße 3 bis 13": "bezirk:Donaustadt",
    "Stadlauer Straße 34 bis 36": "bezirk:Donaustadt",
    "Stadlauer Straße 38 bis 44": "bezirk:Donaustadt",
    "Stillfriedplatz 11-12": "bezirk:Ottakring",
    "Taborstraße 14 bis 16": "bezirk:Leopoldstadt",
    "Taborstraße 15 bis 17": "bezirk:Leopoldstadt",
    "Taborstraße 17a bis 17b": "bezirk:Leopoldstadt",
    "Taborstraße 19 bis 21a": "bezirk:Leopoldstadt",
    "Taborstraße 2": "bezirk:Leopoldstadt",
    "Taborstraße 20 bis 22": "bezirk:Leopoldstadt",
    "Taborstraße 25 bis 29": "bezirk:Leopoldstadt",
    "Taborstraße 28": "bezirk:Leopoldstadt",
    "Taborstraße 30": "bezirk:Leopoldstadt",
    "Taborstraße 31 bis 33": "bezirk:Leopoldstadt",
    "Taborstraße 35 bis 37": "bezirk:Leopoldstadt",
    "Taborstraße 41 bis 43": "bezirk:Leopoldstadt",
    "Taborstraße 43 bis 45": "bezirk:Leopoldstadt",
    "Taborstraße 44 bis 46a": "bezirk:Leopoldstadt",
    "Taborstraße 48 bis 50": "bezirk:Leopoldstadt",
    "Taborstraße 49 bis 59": "bezirk:Leopoldstadt",
    "Taborstraße 52 bis 54": "bezirk:Leopoldstadt",
    "Taborstraße 59 bis 61": "bezirk:Leopoldstadt",
    "Taborstraße 63": "bezirk:Leopoldstadt",
    "Taborstraße 7 bis 11A": "bezirk:Leopoldstadt",
    "Taborstraße ggü. 21 bis 26": "bezirk:Leopoldstadt",
    "Teschnergasse / Johann-Nepomuk-Vogl-Platz 1 bis 8": "bezirk:Währing",
    "Teschnergasse / Johann-Nepomuk-Vogl-Platz 2 bis ggü. 8": "bezirk:Währing",
    "Thaliastraße 105 bis 109": "bezirk:Ottakring",
    "Thaliastraße 110 bis 116": "bezirk:Ottakring",
    "Thaliastraße 111 bis 117": "bezirk:Ottakring",
    "Thaliastraße 118 bis 124": "bezirk:Ottakring",
    "Thaliastraße 119 bis 123": "bezirk:Ottakring",
    "Thaliastraße 125a bis 125b": "bezirk:Ottakring",
    "Thaliastraße 126 bis 134": "bezirk:Ottakring",
    "Thaliastraße 129 bis 131": "bezirk:Ottakring",
    "Thaliastraße 13 bis 15": "bezirk:Ottakring",
    "Thaliastraße 133": "bezirk:Ottakring",
    "Thaliastraße 141": "bezirk:Ottakring",
    "Thaliastraße 145 bis 147": "bezirk:Ottakring",
    "Thaliastraße 146 bis 148": "bezirk:Ottakring",
    "Thaliastraße 152": "bezirk:Ottakring",
    "Thaliastraße 162 bis 164": "bezirk:Ottakring",
    "Thaliastraße 170": "bezirk:Ottakring",
    "Thaliastraße 21 bis 25": "bezirk:Ottakring",
    "Thaliastraße 29 bis 31": "bezirk:Ottakring",
    "Thaliastraße 35 bis 37": "bezirk:Ottakring",
    "Thaliastraße 38 bis 42": "bezirk:Ottakring",
    "Thaliastraße 39 bis 43": "bezirk:Ottakring",
    "Thaliastraße 4 bis 16": "bezirk:Ottakring",
    "Thaliastraße 44": "bezirk:Ottakring",
    "Thaliastraße 46": "bezirk:Ottakring",
    "Thaliastraße 49": "bezirk:Ottakring",
    "Thaliastraße 52 bis 54": "bezirk:Ottakring",
    "Thaliastraße 53 bis 55": "bezirk:Ottakring",
    "Thaliastraße 59 bis 61": "bezirk:Ottakring",
    "Thaliastraße 63 bis 65": "bezirk:Ottakring",
    "Thaliastraße 64 bis 68": "bezirk:Ottakring",
    "Thaliastraße 7 bis 9": "bezirk:Ottakring",
    "Thaliastraße 75 bis 79": "bezirk:Ottakring",
    "Thaliastraße 76": "bezirk:Ottakring",
    "Thaliastraße 78": "bezirk:Ottakring",
    "Thaliastraße 80 bis 82": "bezirk:Ottakring",
    "Thaliastraße 81 bis 85": "bezirk:Ottakring",
    "Thaliastraße 84 bis 90": "bezirk:Ottakring",
    "Thaliastraße 87 bis 91": "bezirk:Ottakring",
    "Thaliastraße 92 / Schuhmeierplatz 15 92": "bezirk:Ottakring",
    "Thaliastraße 93 bis 97": "bezirk:Ottakring",
    "Thaliastraße 94 bis 108": "bezirk:Ottakring",
    "Thaliastraße ggü. 133": "bezirk:Ottakring",
    "Thaliastraße Thaliastraße 24 bis Hofferplatz 11": "bezirk:Ottakring",
    "Tivoligasse 1 bis 7-9": "bezirk:Meidling",
    "Tivoligasse 18 bis 20": "bezirk:Meidling",
    "Tivoligasse 2 bis 4-6": "bezirk:Meidling",
    "Tivoligasse 7-9": "bezirk:Meidling",
    "Unbenannte Verkehrsfläche": "bezirk:Mariahilf",
    "Wagramer Straße 107 bis 113": "bezirk:Donaustadt",
    "Wagramer Straße 108 bis 116": "bezirk:Donaustadt",
    "Wagramer Straße 115 bis 123": "bezirk:Donaustadt",
    "Wagramer Straße 118 bis 126": "bezirk:Donaustadt",
    "Wagramer Straße 20 bis 22": "bezirk:Donaustadt",
    "Wagramer Straße 24": "bezirk:Donaustadt",
    "Wagramer Straße 28-30 bis 36A": "bezirk:Donaustadt",
    "Währinger Straße 110 bis 118": "bezirk:Währing",
    "Währinger Straße 115 bis 117-119": "bezirk:Währing",
    "Währinger Straße 120": "bezirk:Währing",
    "Währinger Straße 121 bis 123": "bezirk:Währing",
    "Währinger Straße 125 bis 141": "bezirk:Währing",
    "Währinger Straße 126 bis 132A": "bezirk:Währing",
    "Währinger Straße 134 bis 146": "bezirk:Währing",
    "Währinger Straße 147 bis 149": "bezirk:Währing",
    "Währinger Straße 148 bis 160": "bezirk:Währing",
    "Währinger Straße 71 bis 75": "bezirk:Währing",
    "Währinger Straße 77 bis 79": "bezirk:Währing",
    "Währinger Straße 80-82 bis 84": "bezirk:Währing",
    "Währinger Straße 81 bis 87": "bezirk:Währing",
    "Währinger Straße 86 bis 106": "bezirk:Währing",
    "Währinger Straße 93": "bezirk:Währing",
    "Währinger Straße 97 bis 107": "bezirk:Währing",
    "Währinger Straße ggü. 143 bis ggü. 149": "bezirk:Währing",
    "Wallensteinstraße 16 bis 20": "bezirk:Brigittenau",
    "Wallensteinstraße 2 bis 6": "bezirk:Brigittenau",
    "Wallensteinstraße 21 bis 23": "bezirk:Brigittenau",
    "Wallensteinstraße 22 bis 28": "bezirk:Brigittenau",
    "Wallensteinstraße 25 bis 31": "bezirk:Brigittenau",
    "Wallensteinstraße 3 bis 7": "bezirk:Brigittenau",
    "Wallensteinstraße 8": "bezirk:Brigittenau",
    "Wallensteinstraße 9 bis 15": "bezirk:Brigittenau",
    "Wiedner Hauptstraße 18 bis 18": "bezirk:Wieden",
    "Wiedner Hauptstraße 22 bis 26": "bezirk:Wieden",
    "Wiedner Hauptstraße 31 bis 33": "bezirk:Wieden",
    "Wiedner Hauptstraße 38 bis 44": "bezirk:Wieden",
    "Wiedner Hauptstraße 56 bis 58": "bezirk:Wieden",
    "Wiedner Hauptstraße 60 bis 60B": "bezirk:Wieden",
    "Wiedner Hauptstraße 65 bis 67": "bezirk:Wieden",
    "Wiedner Hauptstraße 9 bis 11": "bezirk:Wieden",
    "Wielandgasse 10 bis 20": "bezirk:Favoriten",
    "Wielandplatz 5 bis 6": "bezirk:Favoriten",
  },
  "utrecht": {
    "1100": "1100",
    "1200": "1200",
    "2100": "2100",
    "2200": "2200",
    "3100": "3100",
    "3200": "3200",
    "3300": "3300",
    "3400": "3400",
    "3500": "3500",
    "4100": "4100",
    "4600": "4600",
    "5100": "bezirk:West",
    "5200": "5200",
    "5300": "5300",
    "5400": "5400",
    "6100": "6100",
    "6200": "6200",
    "6300": "6300",
    "6400": "6400",
    "6500": "6500",
    "6600": "6600",
    "6700": "6700",
    "7100": "7100",
    "7200": "7200",
    "7300": "7300",
    "7600": "7600",
    "7700": "7700",
    "7800": "7800",
    "8100": "8100",
    "8200": "8200",
    "8300": "8300",
    "9100": "9100",
    "10100": "10100",
    "10200": "10200",
    "10300": "10300",
    "10400": "10400",
    "10500": "10500",
    "11100": "11100",
    "12100": "12100",
    "12200": "12200",
    "12400": "12400",
    "12500": "12500",
    "12600": "12600",
    "12700": "12700",
    "13100": "13100",
    "13200": "13200",
    "13300": "13300",
    "14100": "14100",
    "14200": "14200",
    "14300": "bezirk:West",
    "14400": "14400",
    "15100": "15100",
    "16100": "16100",
    "16300": "16300",
    "16600": "16600",
    "16700": "16700",
    "16800": "16800",
    "17100": "17100",
    "18100": "18100",
    "19100": "19100",
    "20100": "20100",
    "21100": "21100",
    "30100": "30100",
    "30200": "30200",
    "31100": "31100",
    "99900": "bezirk:Noordwest",
  },
  "denhaag": {
    "T01": "T01",
    "T01A": "T01A",
    "T01B": "T01B",
    "T01E": "T01E",
    "T01G": "bezirk:Centrum",
    "T01I": "T01I",
    "T08": "T08",
    "T08A": "bezirk:Archipelbuurt",
    "T08B": "bezirk:Archipelbuurt",
    "T08C": "bezirk:Van Stolkpark en Scheveningse Bosjes",
    "T08D": "T08D",
    "T10": "T10",
    "T10A": "bezirk:Benoordenhout",
    "T10B": "T10B",
    "T10C": "bezirk:Benoordenhout",
    "T10D": "bezirk:Benoordenhout",
    "T10E": "T10E",
    "T11": "T11",
    "T11F": "T11F",
    "T11H": "T11H",
    "T11J": "T11J",
    "T12": "T12",
    "T12A": "bezirk:Valkenboskwartier",
    "T12B": "bezirk:Bomen- en Bloemenbuurt",
    "T12C": "bezirk:Regentessekwartier",
    "T12F": "bezirk:Regentessekwartier",
    "T12G": "T12G",
    "T12H": "bezirk:Regentessekwartier",
    "T12I": "bezirk:Valkenboskwartier",
    "T14": "T14",
    "T15": "bezirk:Waldeck",
    "T16": "bezirk:Ypenburg",
    "T16A": "T16A",
    "T18B": "T18B",
    "T18C": "T18C",
    "T18F": "bezirk:Laakkwartier en Spoorwijk",
    "T19": "T19",
    "T19A": "T19A",
    "T19B": "T19B",
    "T20": "bezirk:Loosduinen",
    "T21": "bezirk:Mariahoeve en Marlot",
    "T22": "T22",
    "T22A": "T22A",
    "T22B": "bezirk:Morgenstond",
    "T24": "bezirk:Haagse Bos",
    "T25": "T25",
    "T26": "T26",
    "T26A": "T26A",
    "T27": "T27",
    "T28": "T28",
    "T28A": "T28A",
    "T29": "T29",
    "T30": "T30",
    "T30A": "T30A",
    "T30B": "bezirk:Schildersbuurt",
    "T30D": "T30D",
    "T31": "T31",
    "T31A": "T31A",
    "T32": "T32",
    "T32B": "T32B",
    "T32C": "T32C",
    "T32D": "bezirk:Transvaalkwartier",
    "T32E": "bezirk:Groente- en Fruitmarkt",
    "T32F": "bezirk:Schildersbuurt",
    "T32H": "T32H",
    "T32V": "T32V",
    "T33": "T33",
    "T33A": "bezirk:Valkenboskwartier",
    "T33B": "bezirk:Valkenboskwartier",
    "T37": "T37",
    "T38": "T38",
    "T39": "T39",
    "T43": "T43",
    "T43B": "T43B",
    "T43F": "T43F",
    "T43H": "T43H",
    "T43I": "bezirk:Scheveningen",
    "T43J": "T43J",
    "T43K": "bezirk:Scheveningen",
    "T43M": "T43M",
    "T43N": "bezirk:Belgisch Park",
    "T43O": "T43O",
    "T43P": "T43P",
    "T43S": "T43S",
    "T43T": "bezirk:Duindorp",
    "T43V": "bezirk:Scheveningen",
    "T43W": "T43W",
    "T50": "bezirk:Oostduinen",
  },
  "rotterdam": {
    "10": "10",
    "11": "11",
    "12": "bezirk:Rotterdam Centrum",
    "20": "20",
    "21": "21",
    "30": "30",
    "31": "31",
    "40": "40",
    "41": "41",
    "42": "42",
    "50": "50",
    "51": "51",
    "60": "60",
    "120": "120",
    "121": "121",
    "200": "200",
    "201": "201",
    "202": "202",
    "204": "bezirk:Charlois",
    "210": "210",
    "220": "220",
    "230": "230",
    "232": "232",
    "240": "240",
    "250": "250",
    "251": "bezirk:Charlois",
    "260": "260",
    "270": "270",
    "271": "bezirk:Charlois",
    "280": "280",
    "281": "bezirk:Charlois",
    "282": "282",
    "290": "290",
    "291": "291",
    "292": "292",
    "300": "300",
    "301": "301",
    "310": "310",
    "311": "bezirk:Feijenoord",
    "312": "bezirk:Feijenoord",
    "320": "320",
    "321": "bezirk:Feijenoord",
    "322": "322",
    "323": "bezirk:Feijenoord",
    "330": "330",
    "331": "331",
    "340": "340",
    "341": "bezirk:Feijenoord",
    "350": "350",
    "370": "370",
    "380": "380",
    "381": "bezirk:Feijenoord",
    "400": "400",
    "410": "410",
    "500": "500",
    "501": "501",
    "502": "502",
    "503": "bezirk:Delfshaven",
    "504": "bezirk:Delfshaven",
    "510": "510",
    "511": "511",
    "513": "513",
    "514": "bezirk:Delfshaven",
    "520": "520",
    "521": "bezirk:Nieuw Mathenesse",
    "530": "530",
    "531": "531",
    "532": "532",
    "540": "540",
    "560": "560",
    "570": "570",
    "571": "bezirk:Delfshaven",
    "580": "580",
    "581": "581",
    "600": "600",
    "610": "610",
    "620": "620",
    "621": "bezirk:Kralingen-Crooswijk",
    "630": "630",
    "632": "bezirk:Kralingen-Crooswijk",
    "633": "633",
    "634": "634",
    "635": "bezirk:Kralingen-Crooswijk",
    "640": "640",
    "650": "650",
    "651": "651",
    "652": "bezirk:Kralingen-Crooswijk",
    "653": "bezirk:Kralingen-Crooswijk",
    "660": "660",
    "670": "670",
    "680": "680",
    "690": "690",
    "700": "700",
    "710": "710",
    "712": "712",
    "720": "720",
    "721": "721",
    "722": "bezirk:Noord",
    "723": "723",
    "724": "724",
    "730": "730",
    "731": "bezirk:Noord",
    "740": "740",
    "750": "750",
    "751": "751",
    "752": "bezirk:Noord",
    "753": "753",
    "760": "760",
    "800": "800",
    "801": "bezirk:Hillegersberg-Schiebroek",
    "811": "811",
    "812": "812",
    "900": "900",
    "910": "910",
    "911": "bezirk:IJsselmonde",
    "912": "912",
    "920": "920",
    "921": "bezirk:IJsselmonde",
    "930": "930",
    "931": "bezirk:IJsselmonde",
    "950": "950",
    "951": "bezirk:IJsselmonde",
    "960": "960",
    "980": "980",
  },
  "groningen": {
    "3001": "3001",
    "3002": "bezirk:Centrum",
    "3003": "3003",
    "3004": "3004",
    "3005": "3005",
    "3006": "3006",
    "3007": "3007",
    "3008": "3008",
    "3009": "3009",
    "3010": "3010",
    "3012": "3012",
    "3014": "3014",
    "3015": "bezirk:Zuidwest",
    "3016": "bezirk:Oud-Zuid",
    "3018": "bezirk:Noordwest",
    "3019": "3019",
    "3020": "3020",
    "3021": "bezirk:Oud-West",
    "3022": "3022",
    "3023": "bezirk:Helpman e.o.",
    "3024": "3024",
    "3026": "bezirk:Centrum",
    "3027": "3027",
    "3028": "3028",
    "3029": "3029",
    "3031": "bezirk:Helpman e.o.",
    "3032": "3032",
    "3033": "3033",
    "3037": "3037",
    "3038": "3038",
    "3039": "3039",
    "3040": "3040",
    "3042": "3042",
    "3043": "bezirk:Helpman e.o.",
    "3044": "3044",
    "3045": "bezirk:Noordwest",
    "3046": "3046",
    "3050": "3050",
    "3051": "bezirk:Haren-West e.o.",
  },
  "nijmegen": {
    "ZONE_CEN": "ZONE_CEN",
    "ZONE_D": "ZONE_D",
    "ZONE_DOD": "bezirk:Nijmegen-Centrum",
    "ZONE_DOH": "bezirk:Nijmegen-Centrum",
    "ZONE_GB": "bezirk:Nijmegen-Centrum",
    "ZONE_J": "ZONE_J",
    "ZONE_K": "ZONE_K",
    "ZONE_L": "ZONE_L",
    "ZONE_LM": "bezirk:Nijmegen-Centrum",
    "ZONE_OS": "ZONE_OS",
    "ZONE_P": "ZONE_P",
    "ZONE_P4": "bezirk:Nijmegen-Centrum",
    "ZONE_P7": "bezirk:Nijmegen-Centrum",
    "ZONE_P8": "bezirk:Nijmegen-Centrum",
    "ZONE_Q": "ZONE_Q",
    "ZONE_R": "ZONE_R",
    "ZONE_RING1": "ZONE_RING1",
    "ZONE_RING2": "ZONE_RING2",
    "ZONE_S": "ZONE_S",
    "ZONE_S1": "ZONE_S1",
    "ZONE_STAT": "bezirk:Nijmegen-Centrum",
    "ZONE_TB": "bezirk:Nijmegen-Centrum",
    "ZONE_V": "ZONE_V",
    "ZONE_W": "ZONE_W",
    "ZONE_WK": "bezirk:Nijmegen-Centrum",
    "ZONE_WW": "bezirk:Lindenholt",
    "ZONE_X": "ZONE_X",
    "ZONE_Y": "ZONE_Y",
    "ZONE_Z": "ZONE_Z",
  },
  "eindhoven": {
    "A11": "A11",
    "B11": "B11",
    "B21": "B21",
    "B2WERK": "B2WERK",
    "B42": "bezirk:Oud-Strijp",
    "B51": "B51",
    "C11": "C11",
    "C13": "C13",
    "C15": "bezirk:Oud-Tongelre",
    "C21": "C21",
    "C23": "C23",
    "C34": "C34",
    "M1": "M1",
  },
  "genf": {
    "A": "A",
    "B": "B",
    "C": "C",
    "D": "D",
    "E": "E",
    "F": "F",
    "G": "G",
    "H": "H",
    "I": "I",
    "J": "J",
    "K": "K",
    "L": "L",
    "M": "M",
    "N": "N",
    "O": "O",
    "P": "P",
    "Q": "Q",
  },
  "krakau": {
    "A1": "A1",
    "A13": "A13",
    "A2": "A2",
    "A20": "A20",
    "A3": "A3",
    "A4": "A4",
    "A6": "A6",
    "B10": "B10",
    "B11": "B11",
    "B12": "B12",
    "B30": "B30",
    "B5": "B5",
    "C15": "C15",
    "C16": "C16",
    "C19": "C19",
    "C21": "C21",
    "C22": "C22",
    "C23": "C23",
    "C24": "C24",
    "C31": "C31",
    "C7": "C7",
    "C8": "C8",
    "C9": "C9",
  },
  "kassel": {
    "BW1": "BW1",
    "BW2": "BW2",
    "BW3": "BW3",
    "II": "II",
    "III": "III",
    "IV": "IV",
    "IX": "IX",
    "RO1": "RO1",
    "RO2": "RO2",
    "RO3": "RO3",
    "RO4": "RO4",
    "SÜ1": "SÜ1",
    "SÜ2": "SÜ2",
    "UN1": "UN1",
    "UN2": "UN2",
    "V": "V",
    "VI": "VI",
    "VIII": "VIII",
    "VW2": "VW2",
    "VW3": "VW3",
    "VW4": "VW4",
    "VW5": "VW5",
    "VW6": "VW6",
    "VW7": "VW7",
    "WH1": "WH1",
    "WH2": "WH2",
    "WH3": "WH3",
    "WT1": "WT1",
    "Zentrum": "Zentrum",
  },
  "essen": {
    "Innenstadt Nord": "Innenstadt Nord",
    "Innenstadt Süd": "Innenstadt Süd",
    "Museum-Nord (II)": "Museum-Nord (II)",
    "Museum-Ost (III)": "Museum-Ost (III)",
    "Museum-Süd (V)": "Museum-Süd (V)",
    "Museum-West (IV)": "Museum-West (IV)",
    "Ostviertel": "Ostviertel",
    "Ostviertel 2": "Ostviertel 2",
    "Sternviertel (I)": "Sternviertel (I)",
  },
  "saarbruecken": {
    "A1": "A1",
    "A2": "A2",
    "A3": "A3",
    "B1": "B1",
    "B2": "B2",
    "C1": "C1",
    "C2": "C2",
    "D1": "D1",
    "D2": "D2",
    "E1": "E1",
    "E2": "E2",
    "F1": "F1",
    "F2": "F2",
    "F3": "F3",
    "H1": "H1",
    "H2": "H2",
    "I1": "I1",
    "I2": "I2",
    "J": "J",
    "L1": "L1",
    "L2": "L2",
    "L3": "L3",
    "N1": "N1",
    "N2": "N2",
    "N3": "N3",
    "R": "R",
    "U": "U",
  },
  "strasbourg": {
    "orange 1": "orange 1",
    "orange 11": "orange 11",
    "orange 12": "orange 12",
    "orange 4": "orange 4",
    "orange 6": "orange 6",
    "orange 7": "orange 7",
    "orange 8": "orange 8",
    "rouge 10": "rouge 10",
    "rouge 13": "rouge 13",
    "rouge 14": "rouge 14",
    "rouge 17": "rouge 17",
    "rouge 9": "rouge 9",
    "vert 16": "vert 16",
    "vert 18": "vert 18",
    "vert 19": "vert 19",
    "vert 2": "vert 2",
    "vert 20": "vert 20",
    "vert 3": "vert 3",
    "vert 5": "vert 5",
  },
}

/** Zahl der Einheiten je Stadt, auch der stillen — der Nenner der Basisrate. */
export const UNIT_COUNTS: Readonly<Record<string, number>> = {
  "berlin": 103,
  "hamburg": 80,
  "frankfurt": 27,
  "muenchen": 82,
  "koeln": 45,
  "duesseldorf": 44,
  "karlsruhe": 13,
  "freiburg": 21,
  "cottbus": 5,
  "rostock": 10,
  "schwerin": 10,
  "graz": 23,
  "salzburg": 38,
  "innsbruck": 20,
  "bern": 31,
  "zuerich": 2,
  "wien": 45,
  "utrecht": 65,
  "denhaag": 77,
  "rotterdam": 104,
  "groningen": 35,
  "nijmegen": 20,
  "eindhoven": 13,
  "genf": 17,
  "krakau": 23,
  "kassel": 29,
  "essen": 9,
  "saarbruecken": 27,
  "strasbourg": 19,
}

/** Die Einheit einer Zone, oder null, wenn die Stadt oder der Schlüssel unbekannt ist. */
export function unitOfZone(city: string, zoneKey: string): string | null {
  return ZONE_UNITS[city]?.[zoneKey] ?? null
}
